src/controller_ref.rs
src/podutils.rs

This changes `assert_eq!(true, ...)` to `assert!(...)` and `assert_eq!(false, ...)` to `assert!(!...)`

TIL about assert!

---

src/client.rs
src/controller.rs
src/controller_ref.rs
src/crd.rs
src/finalizer.rs
src/history.rs
src/k8s_errors.rs
src/lib.rs
src/metadata.rs
src/podutils.rs
src/reconcile.rs

See https://doc.rust-lang.org/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html#creating-idiomatic-use-paths

Move to recommended "best practice" on imports.

---

src/metadata.rs

It would take the name of the passed in object which makes for correct metadata but it doesn't help us at all.
We usually want to create metadata for a new "child" object that should take a new name.

Fix build_metadata method.

---

src/error.rs
src/label_selector.rs
src/lib.rs

Assigning both @soenkeliebau and @maltesander .
Malte: I don't like the tests....there must be an easier way with rstest or something similar, no?
Any ideas?

Helper method to convert LabelSelector to query string

---

Cargo.toml
src/client.rs
src/controller.rs
src/finalizer.rs
src/reconcile.rs

BREAKING CHANGE: This means that adding and removing finalizers is now optional

feat: Move the finalization handling out of the Controller

---

Cargo.toml
src/client.rs
src/k8s_utils.rs
src/lib.rs
src/pod_utils.rs
src/reconcile.rs

To be more consistent with the other modules

Rename podutils to pod_utils

---

src/error.rs
src/lib.rs
src/namespace.rs
src/validation.rs

* Supports getting namespaces to watch for operators using an environment variable
* Supports validating namespace names

feature: Namespace support

---

src/command_controller.rs
src/config_map.rs
src/crd.rs
src/finalizer.rs
src/history.rs
src/metadata.rs
src/role_utils.rs
tests/test_crd.rs

Removed some unnecessary clones and made the kubernetes client a reference where possible.
This will require adaptation in the operators.

Code optimisation

---

src/client.rs

This is a workaround until #113 can be properly investigated.

Add force to Patch parameters in certain scenarios

---

src/pod_utils.rs

https://github.com/stackabletech/operator-rs/issues/128

[#128] - pod_utils::get_pod_condition should take a PodConditionType

---

Cargo.toml
src/client.rs
src/config_map.rs
src/controller_ref.rs
src/finalizer.rs
src/krustlet.rs
src/label_selector.rs
src/metadata.rs
src/pod_utils.rs
src/reconcile.rs
src/test.rs

This has some breaking changes for downstream users but will allow us to treat Crds generic
https://github.com/clux/kube-rs/blob/master/CHANGELOG.md
https://github.com/Arnavion/k8s-openapi/blob/master/CHANGELOG.md

Update kube-rs to 0.57 and k8s-openapi to 0.12

---

src/logging.rs

Fixes #189 
Tested locally with the zookeeper-operator.

Set log level to info by default/issue189

---

src/builder.rs

Required to be able to run pods and containers with users other than root.
Part of https://github.com/stackabletech/issues/issues/59

Added PodSecurityContextBuilder

---

src/builder.rs

Part of https://github.com/stackabletech/issues/issues/59

Added windows security context properties.

---

Cargo.toml

Prepare Cargo.toml for the first release.

Prepare for release.

---

CHANGELOG.md
Cargo.toml

Release 0.1.0. DO NOT SQUASH MERGE!

Release 0.1.0

---

CHANGELOG.md
src/cli.rs
src/lib.rs
src/name_utils.rs
src/status.rs
src/versioning.rs

First tests (with zookeeper) work.

Extracted the versioning from the operators, added required traits for generic access

---

CHANGELOG.md
Cargo.toml
src/scheduler.rs

Implement getter for PodIdentity fields.

---

CHANGELOG.md
Cargo.toml

Release 0.2.1. DO NOT SQUASH MERGE!

Release 0.2.1

---

CHANGELOG.md
Cargo.toml
src/builder.rs

Bumped kube-rs to 0.60

---

CHANGELOG.md

Corrected change log

---

Cargo.toml

Changed product-config dependency to main branch.

---

CHANGELOG.md
src/builder.rs
src/configmap.rs
src/identity.rs
src/k8s_utils.rs
src/pod_utils.rs
src/reconcile.rs

These are used by the STFU operator rework.

Add probe and pod template builders

---

CHANGELOG.md
src/builder.rs
src/controller.rs

This is required for new-style (STFU) operators to be able to customize scheduling

Add node_selector to PodBuilder

---

CHANGELOG.md
src/controller.rs

Sometimes this is intermittent, but it can also be caused by deeper issues
(such as networking problems or RBAC issues) that require manual human attention.

Warn on controller watch failures

---

CHANGELOG.md
Cargo.toml
src/client.rs
src/reconcile.rs
src/role_utils.rs

Import RoleGroupRef from ZooKeeper STFU branch

---

.github/workflows/rust.yml
bors.toml

- Adds bors config
- Removes unneeded clean action from cargo test
- Updates cargo-deny action

Adds bors + actions cleanup

---

CHANGELOG.md
src/crd.rs
src/lib.rs

Refine CRD deprecations

---

CHANGELOG.md
Cargo.toml

Release 0.6.0. DO NOT SQUASH MERGE!

Release 0.6.0

---

CHANGELOG.md

Add note about upgrading kube to changelog

---

CHANGELOG.md
Cargo.toml

Release 0.8.0. DO NOT SQUASH MERGE!

Release 0.8.0

---

CHANGELOG.md
src/client.rs

This is required for the patch to actually go through.

Send object identity when applying status

---

CHANGELOG.md
Cargo.toml

Release 20220127123354

---

CHANGELOG.md
Cargo.toml

Release 0.10.0. DO NOT SQUASH MERGE!

Release 0.10.0

---

src/builder.rs

I might have a few more builder setters for common use cases, that i'd like to upstream if that's OK
I prefer to send them in individual PRs, but if this doesn't work let me know

ContainerBuilder now sets resources

---

CHANGELOG.md
Cargo.toml

kube-rs: 0.68.0 -> 0.69.0

---

CHANGELOG.md
Cargo.toml
src/client.rs
src/crd.rs
src/error.rs
src/logging/controller.rs
src/logging/k8s_events.rs

Misc cleanup

---

CHANGELOG.md
Cargo.toml

Upgrade to K8s 1.23

---

CHANGELOG.md
src/builder.rs

Builder enhancements

---

src/builder.rs
src/product_config_utils.rs

Fix Rust 1.59 warnings

---

CHANGELOG.md
Cargo.toml
stackable-operator-derive/Cargo.toml

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Release 0.45.0

---

Cargo.toml
stackable-operator-derive/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.45.1

---

CHANGELOG.md
src/cpu.rs
src/memory.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Implement Sum for CpuQuantity and MemoryQuantity

---

CHANGELOG.md
src/memory.rs

Leftover of #636
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

refactor: Test

---

CHANGELOG.md
src/memory.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Implement Display for MemoryQuantity

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Bump product-config to 0.5.0

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Releae 0.47.0

---

CHANGELOG.md
src/builder/pod/container.rs
src/builder/pod/mod.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add PodBuilder::termination_grace_period_seconds

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.48.0

---

Cargo.toml

The prebuilt binary has been dropped in 1.0.184.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Unpin serde

---

CHANGELOG.md
src/builder/pod/volume.rs

Depends on https://github.com/stackabletech/secret-operator/pull/314.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Added tls pkcs12 password support to secret volume builder

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.50.0

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.51.0

---

CHANGELOG.md
src/commons/pdb.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix a typo in the documentation of the PdbConfig struct

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.51.1

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.52.0

---

src/commons/pdb.rs
src/role_utils.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Improve wording

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.52.1

---

CHANGELOG.md
Cargo.toml

Needed for https://github.com/stackabletech/secret-operator/pull/306
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.53.0

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.54.0

---

CHANGELOG.md
src/builder/event.rs
src/product_logging/framework.rs

Convert the format of the Vector configuration from TOML to YAML
Vector 0.33.0 uses the YAML file format by default.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Convert the format of the Vector configuration from TOML to YAML

---

deny.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add "Unlicense" license to allowed licenses

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/product_config_utils.rs

Part of https://github.com/stackabletech/product-config/issues/95

refactor: Update product-config

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.56.1

---

CHANGELOG.md
src/commons/affinity.rs
src/commons/cluster_operation.rs
src/commons/opa.rs
src/commons/pdb.rs
src/commons/product_image_selection.rs
src/commons/resources.rs
src/commons/s3.rs
src/product_logging/spec.rs
src/role_utils.rs

Documentation added to core CRD components. The documentation shows up in the final CRD and then also in https://crds.stackable.tech/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

More documentation on core CRD structs

---

CHANGELOG.md
src/commons/product_image_selection.rs

See changelog.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fixed appVersion label in case container images contain a hash

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.58.0

---

src/commons/mod.rs
src/commons/pod_overrides.rs
src/role_utils.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

refactor: Add some tests for podOverrides

---

CHANGELOG.md
Cargo.toml

New doc stuff
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.58.1

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.59.0

---

src/commons/authentication/ldap.rs

… to liberate each operator from having to do it
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: add ldap endpoint helper 

---

CHANGELOG.md
Cargo.toml

Add missing changelog entry pertaining to #705 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: update changelog for 0.60.0

---

CHANGELOG.md
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release 0.60.1

---

src/kvp/annotation/mod.rs
src/kvp/label/mod.rs
src/kvp/mod.rs

feat: Add generic types for `TryFrom<BTreeMap<K, V>>` impl

---

CHANGELOG.md
Cargo.toml

chore: Release operator-rs `0.61.0`

---

src/kvp/mod.rs

Came up in https://github.com/stackabletech/hdfs-operator/pull/454
This PR adds more context to the key/value pair error variants which should make it easier for the user to identify the erroneous pair.

refactor: Add context to key/value pair error variants

---

CHANGELOG.md
src/kvp/consts/keys.rs
src/kvp/consts/mod.rs
src/kvp/consts/values.rs
src/kvp/label/mod.rs

Part of https://github.com/stackabletech/issues/issues/188

feat: Add Stackable vendor label to recommended labels

---

CHANGELOG.md

Fix wrong entry in the changelog

chore: Fix wrong entry in the changelog

---

CHANGELOG.md
Cargo.toml

chore: Release version 0.64.0

---

CHANGELOG.md

This is a follow-up PR to add an entry to the changelog for changes introduced in #730. The previous PR accidentally didn't include this entry.

chore: Adjust changelog to include changes from #730

---

.github/workflows/build.yml
.github/workflows/daily_security.yml
.github/workflows/reviewdog.yaml
CHANGELOG.md

Bumps various action versions in GitHub workflows.

ci(deps): Bump action versions

---

crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/Cargo.toml

This release contains a few various features, version bumps, and the improved crate structure.

chore: Release operator-rs 0.65.0

---

crates/stackable-certs/CHANGELOG.md
crates/stackable-certs/Cargo.toml
crates/stackable-operator-derive/CHANGELOG.md
crates/stackable-operator-derive/Cargo.toml
crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/Cargo.toml
crates/stackable-webhook/CHANGELOG.md
crates/stackable-webhook/Cargo.toml

- stackable-certs-0.2.0
- stackable-operator-derive-0.2.0
- stackable-operator-0.66.0
- stackable-webhook-0.2.0
---
_These appear to have already been done as part of the post-release tasks_
```sh
git checkout main
git pull
git log -1 --oneline # ensure the HEAD is the merge commit
git tag -s stackable-certs-0.2.0
git tag -s stackable-operator-derive-0.2.0
git tag -s stackable-operator-0.66.0
git tag -s stackable-webhook-0.2.0
git push --tags
```
```[tasklist]
```
```[tasklist]
```

chore: Release crates

---

Cargo.toml
crates/stackable-certs/CHANGELOG.md
crates/stackable-operator-derive/CHANGELOG.md
crates/stackable-operator/CHANGELOG.md
crates/stackable-webhook/CHANGELOG.md

https://github.com/kube-rs/kube/releases/tag/0.89.0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Bump kube to 0.89.0 and update all dependencies

---

crates/stackable-webhook/Cargo.toml

fix(stackable-webhook): enable axum http2 feature

---

crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/src/commons/listener.rs

Fixup of https://github.com/stackabletech/operator-rs/pull/773
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix!: Move service_external_traffic_policy from ListenerSpec to ListenerClassSpec

---

crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/src/commons/listener.rs

Fixup of https://github.com/stackabletech/operator-rs/pull/773
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore!: Rename KubernetesServiceType back to ServiceType

---

Cargo.lock
Cargo.toml
crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Release stackable-operator 0.68.0

---

crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/src/builder/pod/mod.rs
crates/stackable-operator/src/builder/pod/volume.rs

Part of https://github.com/stackabletech/issues/issues/555
Required for https://github.com/stackabletech/hdfs-operator/pull/534
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add labels to listener volume builder

---

crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/src/commons/product_image_selection.rs

Originally introduced in #629.
Also adds logging because this was pretty confusing to me.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Product image selection: only override version for PR builds

---

Cargo.lock
crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Release stackable-operator v0.71.0

---

Cargo.lock
crates/stackable-operator/CHANGELOG.md
crates/stackable-operator/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Release stackable-operator v0.72.0

---

.github/workflows/build.yml
.github/workflows/daily_security.yml
.github/workflows/pr_pre-commit.yaml
rust-toolchain.toml

Part of https://github.com/stackabletech/operator-rs/issues/898
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Bump Rust version and workflow actions

---

crates/stackable-versioned-macros/fixtures/inputs/k8s/crate_overrides.rs
crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@crate_overrides.rs.snap
crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap
crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap
crates/stackable-versioned-macros/src/attrs/k8s.rs
crates/stackable-versioned-macros/src/codegen/container/mod.rs
crates/stackable-versioned-macros/src/codegen/container/struct.rs
crates/stackable-versioned/CHANGELOG.md

This simplifies the handling and generation of crate overrides.

refactor(stackable-versioned): Simplify crate overrides

---

crates/stackable-versioned-macros/src/codegen/container/mod.rs
crates/stackable-versioned/CHANGELOG.md

Convert the Override type to enum.

refactor(stackable-versioned): Convert Override to enum

---

.github/ISSUE_TEMPLATE/config.yml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix "blank issue" link to actually point at the op-rs repo

---

deny.toml

Pull it from operator-templating, as that's the source of truth here
Closes https://github.com/stackabletech/operator-rs/pull/918
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update deny.toml from operator-templating

---

crates/stackable-telemetry/src/tracing/mod.rs

Part of https://github.com/stackabletech/issues/issues/639

chore: Update RotationPeriod variant casing to snake_case

---

.github/workflows/build.yml

Came up in https://github.com/stackabletech/operator-rs/pull/1026#pullrequestreview-2823957146.
Although, for some reason it wouldn't have catched it
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: Run tests with both no features and all features

---

Cargo.lock
Cargo.toml
crates/stackable-telemetry/src/instrumentation/axum/mod.rs

chore(telemetry): Bump OTel crates
