.github/workflows/rust.yml, src/crd.rs, src/error.rs, src/lib.rs
Github Actions fails because of duplicate features in clippy check and a bad doc test.
This happened because the first commit only added the Github Actions definition.
=> Addresses build problems

src/client.rs, src/crd.rs, src/error.rs, src/finalizer.rs, src/lib.rs
This introduces a "OperatorResult" type which uses our own Error type.
I decided to name it `OperatorResult` instead of reusing the `Result` name.
Personally, I find it confusing to have `Result` mean different things in different places and I tend to get confused.
This also replaces `map_err` with a different way to returning our errors.
This PR depends on #7 so that needs to be merged in first!
=> Introduce result type

Cargo.toml, src/client.rs
There are some things (like Pods) that return the object itself when delete is called, others return a `Status` object instead.
So we have to return an `Either` here and the client will have to know what to expect.
=> Adds a `delete` method.

src/lib.rs
Minor: This allows using the `object_to_owner_reference` method with more objects.
`Meta` requires `Resource` but we only need `Resource`.
Major: This also fixes ConfigMap creation to use the namespace of the resource that's passed in.
=> One minor one major fix

src/podutils.rs
This was a suggestion from the Ferrous Rust Experts and it makes the code nicer to read.
=> Flattens the code a bit by introducing early returns

src/history.rs, src/k8s_errors.rs, src/lib.rs
So far the same "spec" would lead to the same hash which would lead to the same K8S object name which in turn would lead to an "AlreadyExists" error.
This can easily happen if someone changes a spec option and then later reverts that change.
This introduces a collision count which is added to the hash. The idea here is from how StatefulSets operate but I'm sure I don't implement it 100% compatible, I don't think I need to either.
=> Checks for collisions on revision count and try with a new hash

src/lib.rs
The kube controller class requires an error_policy function that handles andy errors during reconciliations.
This adds a very simple requeueing error policy.
=> Error policy

.github/workflows/rust.yml
It probably makes more sense to run the release build only when the tests finished successfully.
Should we want to publish nightly builds this probably makes sense.
=> Merge test & build step

Cargo.toml, src/metadata.rs
This also fixes a bug (not sure how that happened) in the object_to_owner_reference method.
=> Adds a method to build an ObjectMeta object

src/reconcile.rs
This is related to #55 which talks about using labels.
That, however, requires everyone to actually set labels so this is a first leightweight approach that fixes the issue itself but not the performance implications of fetching all pods and then filtering on the client side.
=> This filters pods by owner reference of the current object.

Cargo.toml, src/controller.rs
Create a span for each new reconcile, assign a unique id to each request and improve logging in general
=> Improve logging

src/lib.rs, src/metadata.rs
This was set to false by default which was a bit surprising. We're only using it in a context where we're the controller as well. If we ever need to we can introduce a parameter to say whether it should be set or not but for now we'll just change the default.
=> fix: object_to_owner_reference now sets the controller flag.

src/controller.rs
Some errors don't require a scary !error log message.
=> Better error handling in Controller

src/history.rs, src/lib.rs, src/metadata.rs
This only works when the garbage collector is also running otherwise the object will never be cleaned up.
The garbage collector does not run as part of the apiserver itself. It's probably controller-manager or something.
=> Optionally set the block_owner_deletion flag in OwnerReferences for automatic cleanup

Cargo.toml
This is not needed here and can lead to problems because it pulls in kube-derive with default features which doesn't allow downstream users to easily opt-out of the schema feature.
=> Removes the `derive` feature from kube

src/controller_utils.rs, src/lib.rs
This returns a hashed value of the object passed in and includes an optional collision count to avoid collisions for two otherwise same objects.
=> Adds a compute_hash method

Cargo.toml, src/lib.rs, src/validation.rs
This is a translation from the Kubernetes validation package. But only a very small part of it.
=> Adds validation methods for well-formed names

src/client.rs, src/history.rs
BREAKING CHANGE: `list` in `Client` now requires a `ListParam` parameter
=> feat: List with selector

.github/workflows/rust.yml, CONTRIBUTING.adoc, README.adoc, src/client.rs, src/crd.rs, src/error.rs, tests/test_crd.rs
Attempt to implement CRD creation retry. Added an optional timeout for that. One frequent reason why CRDs fail to be created are permissions - the retry won't help here, it will simply time out, unless permissions are adjusted in time.
There is a basic `test_ensure_crd_created` introduced. It is **not** ignored by default and it requires Kubernetes and `KUBECONFIG` environment variable set. Could be ignored by default to make tests runnable locally by anyone. Running Kubernetes cluster in GitHub actions is simple - there is a ready `debianmaster/actions-k3s` available. Exposes the `KUBECONFIG` var automatically, with `clusteradmin` permissions enabled by default (all permissions basically).
If left enabled, anyone who'll do `cargo test` will see tests failed, unles the above mentioned …
=> The 'ensure_crd_created' method retries on failure.

src/client.rs, src/command_controller.rs, src/history.rs, src/reconcile.rs, src/role_utils.rs
Originally added namespaces support to `list_with_label_selector` method. This has been implemented in the meantime already and merged to main. Therefore, this PR adds the following:
1. Namespaces are passed as string slices, therefore no strings are moved or even cloned anymore.
2. Tests
=> [89] - list_with_label_selector namespace as a ref + tests

src/reconcile.rs
/closes #140 
I checked and the trait bound on Clone is still needed after all because of 
```
impl<K> Api<K>
where
K: Clone + DeserializeOwned + Debug,
```
in `core_methods.rs` in `kube-rs`
=> Remove comment about unneeded trait bounds

.github/workflows/rust.yml, Cargo.toml, src/client.rs, src/crd.rs, src/error.rs, tests/test_crd.rs
The function also allows specifying a timeout and delay between retries to optionally allow operators to wait until CRDs have been created and then continue their startup.
partially fixes https://github.com/stackabletech/issues/issues/27
follow up PRs are needed in all operators for to fully fix the issue.
=> Adds function to check by name if all required CRDs have been registered in Kubernetes

Cargo.toml, src/controller.rs
Due to https://github.com/kube-rs/kube-rs/pull/575 we had to change the type bounds on the owns function, as this doesn't support DynamicTypes anymore.
This _should_ not require any changes in the operators themselves, as we don't currently use DynamicTypes. Might break for people who do though.
=> Updated kube and kube-runtime to 0.58

src/command_controller.rs
I made a mistake when introducing the builder patterns and created a ObjectMeta instead of an OwnerReference by accident.
=> Fix command controller

src/lib.rs, src/utils.rs
This is related to https://github.com/stackabletech/issues/issues/19
I don't think we can include the full `bult` in `operator-rs` because it auto-generates a file at build time (using a `build.rs` script) and if we include this in operator-rs we'd get the information of `operator-rs` and not of the using library.
See https://github.com/stackabletech/spark-operator/pull/118 for an example on how to use it.
=> Adds a simple method to print startup diagnostic information

CHANGELOG.md, src/client.rs
This is required so that different applies don't revert each other. For example, `set_condition` would trample on other conditions set by the same operator (actually, it still does that for another reason, #226).
This is technically breaking (adding a param to the public API), but no Stackable repos currently use the affected methods.
=> Require a context for fieldManager when using Server-Side Apply

CHANGELOG.md, src/controller.rs
This is already provided by kube_runtime::Controller's span (https://github.com/kube-rs/kube-rs/blob/b13c619e699311788bc7cdbb0fdf18176ebd02ef/kube-runtime/src/controller/mod.rs#L274-L277). Maybe we should also move `request_id` upstream?
=> Remove duplicate resource identity from reconciler span

CHANGELOG.md, src/labels.rs
`get_recommended_labels` is too specific (includes stuff like the version number), while `build_common_labels_for_all_managed_resources` is too generic (doesn't include the role (group)).
Also redefines all of the helpers, so that they refine each others' output rather than inserting `APP_NAME_LABEL` in three different places.
=> Add a helper for obtaining the selector labels for a certain role group

CHANGELOG.md, src/product_config_utils.rs, src/role_utils.rs
For products where all roles take the same `Configuration` this means that you no longer need the `Role::into`. However, products that do have roles with different `Configuration` types you now need to use `Role::erase` instead.
=> Don't mandate boxing role configs

CHANGELOG.md, src/configmap.rs, src/product_config_utils.rs, src/status.rs, src/versioning.rs
`Option<&T>` carries the same expressive power, is slightly more efficient, and
makes it easier to express some code with fewer clones.
In general code that provides provides these parameters will need to change from
`&foo` to `foo.as_ref()`, and from `&Some(foo)` to `Some(&foo)`. Rustc has a
specific lint for `as_ref`.
=> Change all instances of &Option<T> to Option<&T>

CHANGELOG.md, src/labels.rs
`role_group_selector_label` isn't helpful for role-level services where we want to LB across all rolegroups.
=> Add label role_selector_label for selecting objects belonging to any rolegroup

CHANGELOG.md, src/cli.rs
=> Exclude `cli::Command` doccomment from `--help`

CHANGELOG.md, Cargo.toml, src/product_config_utils.rs, src/role_utils.rs
=> Default Role/RoleGroup configuration when deserializing

CHANGELOG.md, Cargo.toml, src/cli.rs
This requires some manual work (compared to #288), since Clap is a breaking update. In particular, `structopt::StructOpt` has now been upstreamed as `clap::Parser`.
=> Upgrade Clap to 3.0.4

CHANGELOG.md, Cargo.toml, src/cli.rs
This is useful for secret-operator, which doesn't have a product-config but does care about other options, such as the CSI plugin socket path.
This depends on and builds upon #289.
=> Allow overriding CLI run arg type

CHANGELOG.md, Cargo.toml, src/controller.rs
Kube-rs now supports user impersonation! Run your operators with the environment variable `KUBE_RS_DEBUG_IMPERSONATE_USER=system:serviceaccount:default:my-operator` to run the operator with the same RBAC rules as the ServiceAccount `my-operator` in `default`.
Operator reconcile function signatures will have to change from `async fn reconcile(obj: K, ...)` to `async fn reconcile(obj: Arc<K>, ...)`.
=> Kube: 0.66 -> 0.68

src/builder.rs
=> PodBuilder can now set pod affinity

CHANGELOG.md, src/builder.rs
This causes K8s to generate a bunch of environment variables that may break the system being ran, causing issues such as https://github.com/stackabletech/spark-operator/pull/256.
This is technically breaking, but this "feature" is virtually unused anyway.
=> Disable service links

CHANGELOG.md, src/crd.rs
Inspired by `ZookeeperClusterRef` (including https://github.com/stackabletech/zookeeper-operator/pull/382), but generalized and added some convenience methods.
=> Add `ClusterRef` as discussed at the last architecture meeting

CHANGELOG.md, src/logging/k8s_events.rs
=> Truncate K8s event message if it is too long

CHANGELOG.md, Cargo.toml, src/cli.rs
- Preparation to let operators watch a single namespace
=> Added watch_namespace parameter to `ProductOperatorRun`

CHANGELOG.md, src/logging/k8s_events.rs
=> Truncate events to the actual length limit, rather than a constant amount

.github/pull_request_template.md, .github/workflows/build.yml, .github/workflows/daily_security.yml, .github/workflows/reviewdog.yaml, bors.toml
This enables merge queue support
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Move from bors to merge queue and update github actions dependencies

CHANGELOG.md, src/commons/product_image_selection.rs
Fixup of #619 
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> fix: Support PR versions in automatic stackableVersion

CHANGELOG.md, Cargo.toml, stackable-operator-derive/Cargo.toml
Sample operator PR: https://github.com/stackabletech/trino-operator/pull/458
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(deps): Bump all dependencies (including kube and k8s-openapi)

CHANGELOG.md, Cargo.toml
We can do so, because https://github.com/rustls/rustls/issues/184 was resolved
Tested using stackablectl and zookeeper-op and kind and IONOS
Needed for https://github.com/stackabletech/stackable-cockpit/issues/92
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Switch from openssl to rustls

CHANGELOG.md, Cargo.toml
https://github.com/kube-rs/kube/releases/tag/0.86.0
We already use the rustls stack :rocket: 
Tested using trino-operator, no breaking change there.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> bump: kube to 0.86.0 and k8s version to 1.28

CHANGELOG.md, src/product_config_utils.rs, src/role_utils.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Make roleConfig customizable

CHANGELOG.md, src/duration/mod.rs
This PR adds a check when adding up different duration fragments while parsing using `Duration::from_str`. This function will now return an error, if the duration overflows.
```[tasklist]
```
```[tasklist]
```
=> feat: Add duration overflow check

CHANGELOG.md, src/duration/mod.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Add Duration::from_minutes, hours and days

src/config/merge.rs
Needed for https://github.com/stackabletech/issues/issues/357
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: impl Atomic for Duration

CHANGELOG.md, src/builder/pod/mod.rs, src/error.rs
Part of https://github.com/stackabletech/issues/issues/357
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> refactor!: Change PodBuilder::termination_grace_period to take Duration struct

CHANGELOG.md, src/config/fragment.rs, src/product_logging/spec.rs, stackable-operator-derive/src/fragment.rs
Previously Fragments were missing descriptions in the CRDs, as the doccomments where only available on the original struct, but not the Fragment.
This PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Pass through docs to derived Fragment structs

CHANGELOG.md, Cargo.toml
This PR bumps the version to `0.55.0`.
=> chore: Release 0.55.0

CHANGELOG.md, Cargo.toml, src/commons/product_image_selection.rs
Fixes the problem reported in Slack by @Jimvin 
> For info, the thing that triggered this error for us was using a custom image from a local docker repo which had the port number in the url. I am assuming that it tried to parse everything after the first : character using SemVer, but the error isn’t all that helpful in pointing out what was being parsed.
This seems to be a bug in the parsing of custom image locations with port numbers in the location.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Docker image tag parsing when user specifies custom image

CHANGELOG.md, Cargo.toml
kube `0.86.0` was yanked as mentioned in https://github.com/kube-rs/kube/issues/1316#issuecomment-1824013988
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Bump kube to 0.87.1

CHANGELOG.md, Cargo.toml, src/cli.rs, src/commons/affinity.rs, src/commons/cluster_operation.rs, src/commons/opa.rs, src/commons/pdb.rs, src/commons/product_image_selection.rs, src/commons/s3.rs, src/crd.rs, src/error.rs, src/product_logging/spec.rs, src/role_utils.rs
This is a breaking change.
To fix `main.rs` in the operator, change the CRD generation like so:
Command::Crd => DruidCluster::print_yaml_schema(built_info::CARGO_PKG_VERSION)?,
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Replace docs URL placeholder with versioned docs link in CRD output

CHANGELOG.md, src/commons/authentication/ldap.rs
Noticed in https://github.com/stackabletech/airflow-operator/pull/366
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Let ldap add_volumes_and_mounts also add the needed TLS volumes

src/commons/s3.rs
Fixes a small typo discovered in https://github.com/stackabletech/edc-operator/pull/45
=> chore: Remove typo for S3 bucket doc comment / description

CHANGELOG.md, src/kvp/annotation/mod.rs, src/kvp/label/mod.rs, src/kvp/mod.rs
This PR adds two QoL improvements to the key/value pair API:
- Add `TryFrom<[(K, V); N]>` impl for labels and annotations
- Add `Labels::parse_insert()` and `Annotations::parse_insert()` functions. They take `impl TryInto<_>` as a parameter.
=> feat: Add key/value pair QoL improvements

CHANGELOG.md, src/iter.rs, src/kvp/annotation/mod.rs, src/kvp/label/mod.rs, src/kvp/mod.rs
Fixes #713
It does not directly solve the issue, but `.collect()` only works on types which implement `FromIterator` which must never fail. Implementing `FromIterator for Result<Self, Error>` is also not an option, because we cannot implement a foreign trait on a foreign type. There are now two possible solutions.
```rust
let map = BTreeMap::from([
("stackable.tech/managed-by", "stackablectl"),
("stackable.tech/vendor", "Stackable"),
]);
let labels = map
.iter()
.map(|p| Label::try_from(p))
.collect::<Result<Vec<Label>, LabelError>>()
.unwrap();
let labels = Labels::from_iter(labels);
```
```rust
let map = BTreeMap::from([
("stackable.tech/managed-by", "stackablectl"),
("stackable.tech/vendor", "Stackable"),
]);
// Works on any iterator, like Vec<(String, String)> or &[(&str, &str)]
let …
```
=> feat: Add TryFromIterator trait and implement it for `Labels` and `Annotations`

CHANGELOG.md, src/builder/pod/mod.rs, src/builder/pod/volume.rs
Persistent analogue of `::build()` that is suitable for deploying directly, or for adding to a StatefulSet. Also renamed `::build()` to `::build_ephemeral()` for parity (and to clarify that it isn't, and shouldn't be, the default).
Extracted from https://github.com/stackabletech/hdfs-operator/pull/450.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add ListenerOperatorVolumeSourceBuilder::build_pvc

CHANGELOG.md, src/product_logging/spec.rs
Extracted from https://github.com/stackabletech/hdfs-operator/pull/457.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add Logging::for_container helper

CHANGELOG.md, src/cpu.rs, src/memory.rs
This PR adds Serde `Deserialize` and `Serialize` support for `CpuQuantity` and `MemoryQuantity`.
This change is required for #723.
=> feat: Add Serde impl for CpuQuantity and MemoryQuantity

CHANGELOG.md, src/kvp/key.rs
Came up in https://github.com/stackabletech/hdfs-operator/pull/454.
=> refactor: Change Deref target of KeyPrefix and KeyName to str

CHANGELOG.md, src/commons/authentication/ldap.rs, src/commons/authentication/mod.rs, src/commons/authentication/oidc.rs, src/commons/authentication/static_.rs, src/commons/authentication/tls.rs, src/commons/secret_class.rs
Derive `Hash` and `Ord` instances for `AuthenticationClassProvider`, so that duplicates can be detected.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Derive Hash and Ord instances for AuthenticationClassProvider

CHANGELOG.md, fixtures/helm/input-additional.yaml, fixtures/helm/input-required.yaml, fixtures/helm/output.yaml, src/helm/mod.rs
Part of https://github.com/stackabletech/issues/issues/188, discussed in today's (2024-02-01) meeting, see https://github.com/stackabletech/issues/issues/188#issuecomment-1920967373.
=> refactor: Remove `resources` key from DynamicValues

CHANGELOG.md, src/time/duration.rs
`instant -= duration` is currently defined as `instant += duration`, which is clearly the opposite of what the user requested.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> instant -= duration should actually.. subtract

stackable-webhook/Cargo.toml
Moving the dependency from `dev-dependencies` to `dependencies` resolves issues when using the library in downstream projects, like the product operators.
This came up while writing the webhooks implementation guide (see https://github.com/stackabletech/documentation/pull/561).
=> chore: Move k8s-openapi dependency in `stackable-webhook`

CHANGELOG.md, stackable-webhook/src/lib.rs, stackable-webhook/src/servers/conversion.rs
This adds a little more convenience when using `ConversionWebhookServer`. Users now don't need an additional explicit dependency on `kube` to import the required type.
Came up in https://github.com/stackabletech/documentation/pull/561
=> feat: Add re-export for ConversionReview type in `stackable-webhook`

CHANGELOG.md, Cargo.toml, crates/stackable-operator/src/logging/mod.rs, deny.toml
This PR bumps various Rust dependencies. The changes pass the tests and `cargo check`.
The `opentelemetry-jaeger` crate was recently deprecated for `opentelemetry-otlp`, because Jaeger now natively supports the OTEL protocol. This requires a follow-up PR implementing the required changes.
=> chore(deps): Bump Rust dependencies

CHANGELOG.md, Cargo.toml, crates/stackable-certs/src/ca/mod.rs, crates/stackable-certs/src/keys/ecdsa.rs, crates/stackable-certs/src/keys/rsa.rs, crates/stackable-certs/src/lib.rs, crates/stackable-operator/src/builder/meta.rs, crates/stackable-operator/src/builder/pod/mod.rs, crates/stackable-operator/src/builder/pod/volume.rs, crates/stackable-operator/src/commons/authentication/ldap.rs, crates/stackable-operator/src/commons/authentication/oidc.rs, crates/stackable-operator/src/commons/authentication/tls.rs, crates/stackable-operator/src/commons/secret_class.rs, crates/stackable-operator/src/config/fragment.rs, crates/stackable-operator/src/kvp/mod.rs, crates/stackable-operator/src/product_config_utils.rs, crates/stackable-operator/src/time/duration.rs, crates/stackable-webhook/src/lib.rs, crates/stackable-webhook/src/tls.rs
This change is to encourage testing error variants by type rather than text contents.
- Bump strum to 0.26.2
- Derive `PartialEq` on most _Snafu_ Error enums.
- Add custom implementations of `PartialEq` for _Snafu_ error enums that use types that are not directly comparable.
>[!IMPORTANT] 
> Some variants are impossible to compare, so these implementations are restricted to `#[cfg(test)]` because they cause panics.
```[tasklist]
```
```[tasklist]
```
=> chore: implement PartialEq for most Snafu Error enums

Cargo.toml, crates/stackable-certs/src/ca/mod.rs, crates/stackable-certs/src/keys/mod.rs, crates/stackable-certs/src/keys/rsa.rs
Both me and @sbernauer stumbled over these performance issues during tests.
This PR increases the optimization level for the `rsa` and `stackable-certs` crates during test runs to O3 to speed up the RSA key generation. Additionally, it only uses 512 bit long keys instead of 4096 used in release builds. Further, it also disables two doc tests.
=> test: Improve `stackable-certs` test speeds

crates/stackable-certs/src/ca/mod.rs
Without removing this duplicate extension, the Go X.509 parsing code would error out stating that the "certificate contains duplicate extensions", which was indeed correct.
We accidentally included the authority key identifier twice, once in the leaf profile and once by manually adding the extension after building the cert.
We now removed the manually added extension. This resolved the Go error and the HTTP client was able to establish a TLS-secured connection to the dummy webhook.
See merge: https://go-review.googlesource.com/c/go/+/383215
See code: https://github.com/golang/go/blob/315b6ae682a2a4e7718924a45b8b311a0fe10043/src/crypto/x509/parser.go#L965-L968
---
To be able to access the OID of the duplicate extension, it was required to change Go's standard library. I will provide an …
=> fix: Remove duplicate authority key identifier extension

Cargo.toml, crates/stackable-certs/CHANGELOG.md, crates/stackable-operator-derive/CHANGELOG.md, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/builder/pod/volume.rs, crates/stackable-operator/src/commons/affinity.rs, crates/stackable-operator/src/commons/resources.rs, crates/stackable-webhook/CHANGELOG.md
We need to go throw the breaking change https://github.com/kubernetes/kubernetes/pull/118653, which should not break the API (only the internally used structs)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Bump k8s compilation version to 1.29. Also bump all dependencies

.github/workflows/build.yml
Only run the clippy annotation job when the PR is not marked as a draft. This prevents the bot from spamming comments / reviews, when the PR is known to be in a broken state.
=> ci: Only run clippy annotation job when PR is not a draft

.github/workflows/build.yml, .github/workflows/daily_security.yml, .github/workflows/reviewdog.yaml, CHANGELOG.md, Cargo.toml, crates/stackable-certs/CHANGELOG.md, crates/stackable-operator-derive/CHANGELOG.md, crates/stackable-operator/CHANGELOG.md, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-webhook/CHANGELOG.md
This bumps various action versions in our GitHub workflows.
```[tasklist]
```
=> ci: Bump action versions

Cargo.lock, crates/k8s-version/CHANGELOG.md, crates/stackable-certs/CHANGELOG.md, crates/stackable-certs/Cargo.toml, crates/stackable-operator-derive/CHANGELOG.md, crates/stackable-operator-derive/Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-versioned/CHANGELOG.md, crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/Cargo.toml
Release these crates:
- k8s-version 0.1.0
- stackable-certs 0.3.0
- stackable-operator 0.67.1
- stackable-operator-derive 0.3.0
- stackable-telemetry 0.1.0
- stackable-versioned 0.1.0
- stackable-webhook 0.3.0
=> chore: Release crates

Cargo.lock, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-versioned/src/attrs/field.rs, crates/stackable-versioned/src/gen/field.rs, crates/stackable-versioned/src/gen/mod.rs, crates/stackable-versioned/src/gen/neighbors.rs, crates/stackable-versioned/src/gen/vstruct.rs, crates/stackable-versioned/tests/basic.rs
Tracked by https://github.com/stackabletech/issues/issues/507, follow-up of #764 
```[tasklist]
```
=> feat(stackable-versioned): Improve action chain generation

crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing.rs
It causes infinite cascading events to be emitted. 
See https://github.com/open-telemetry/opentelemetry-rust/issues/761
=> fix(stackable-telemetry): Disable export of h2 events via OTLP

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/product_logging/spec.rs
This PR adds a function to `LogLevel` which converts the `LogLevel` to a log level String understood by OPA.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Add functionality to convert LogLevel to an OPA log level

crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing.rs
Part of https://github.com/stackabletech/issues/issues/531
Now each tracing subscriber log level can be configured via the given environment variable.
```rust
let trace_guard = Tracing::builder()
.service_name("hdfs_operator")
.with_console_output("HDFS_OPERATOR_LOG", LevelFilter::INFO)
.with_otlp_log_exporter("HDFS_OPERATOR_OTLP_LOG", LevelFilter::DEBUG)
.with_otlp_trace_exporter("HDFS_OPERATOR_OTLP_TRACE", LevelFilter::TRACE)
.build();
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat(stackable-telemetry): Add support for env_var per configured subscriber

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/product_logging/spec.rs
Adds the `Display` derive macro to `LogLevel`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: derive strum::Display for LogLevel

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Derive `strum::Display` for `LogLevel`([#805]).
[#805]: https://github.com/stackabletech/operator-rs/pull/805
=> chore: Release stackable-operator 0.69.1

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/product_logging/spec.rs
Set strum::Display for LogLevel to uppercase and add warning.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: set strum::Display for LogLevel to uppercase

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Change `strum::Display` output format for `LogLevel` to uppercase ([#808]).
[#808]: https://github.com/stackabletech/operator-rs/pull/808
=> chore: Release stackable-operator 0.69.2

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Processing of corrupted log events fixed; If errors occur, the error
messages are added to the log event ([#802]).
[#802]: https://github.com/stackabletech/operator-rs/pull/802
=> chore: Release stackable-operator 0.69.3

.github/workflows/build.yml, Cargo.lock, Cargo.toml, crates/k8s-version/src/lib.rs, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/client.rs, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/src/attrs/container.rs, crates/stackable-versioned-macros/src/attrs/field.rs, crates/stackable-versioned-macros/src/gen/field.rs, crates/stackable-versioned-macros/src/gen/mod.rs, crates/stackable-versioned-macros/src/gen/vstruct.rs, crates/stackable-versioned-macros/tests/deprecate.rs, crates/stackable-versioned-macros/tests/rename.rs, crates/stackable-versioned/CHANGELOG.md, deny.toml
Tracked by https://github.com/stackabletech/issues/issues/507
This PR adds a check to ensure that renamed fields don't collide in any of the declared versions. This is currently not ensured and can lead to two or more fields using the same name in a particular version.
=> feat(stackable-versioned): Add collision check for renamed fields

crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/src/tls.rs
> [!NOTE]
> Easier to review with whitespace hidden: https://github.com/stackabletech/operator-rs/pull/815/files?diff=split&w=1
As per https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html,
> In general, issuing a blocking call or performing a lot of compute in a future without yielding is problematic, as it may prevent the executor from driving other futures forward. This function runs the provided closure on a thread dedicated to blocking operations. See the [CPU-bound tasks and blocking code](https://docs.rs/tokio/latest/tokio/index.html#cpu-bound-tasks-and-blocking-code) section for more information.
- Please make sure all these things are …
=> fix(stackable-webhook): Move certificate generation to the blocking thread

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/product_image_selection.rs
Follow-up of https://github.com/stackabletech/operator-rs/pull/817
This way we have a single point of responsibility, which makes it easier to plug in the recommended product version later on, while maintaining the ergonomic API from https://github.com/stackabletech/operator-rs/pull/817.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> refactor: Use ProductImage::product_version internally

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/product_logging/framework.rs
Fix the regular expression for OPA bundle builder logs
The following log entry does not contain a log message:
```
[2m2024-01-01T00:00:00.000000Z[0m [32m INFO[0m [2mbundle[0m[2m:[0m
```
It did not match the regular expression, all fields like the timestamp, level and logger were ignored and the following error was added to the event:
> Log event not parsable: function call error for "parse_regex" at (122:276): could not find any pattern matches
This pull request changes the regular expression to allow an empty message. All other fields are processed correctly and the log event is marked with "Message not found.".
- Please make sure all these …
=> Fix the regular expression for OPA bundle builder logs

crates/k8s-version/CHANGELOG.md, crates/stackable-certs/CHANGELOG.md, crates/stackable-operator-derive/CHANGELOG.md, crates/stackable-operator/CHANGELOG.md, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-versioned/CHANGELOG.md, crates/stackable-webhook/CHANGELOG.md
Create releases for:
- `k8s-version` @ `0.1.1`
- `stackable-certs` @ `0.3.1`
- `stackable-operator-derive` @ `0.3.1`
- `stackable-operator` @ `0.70.0`
- `stackable-telemetry` @ `0.2.0`
- `stackable-versioned` @ `0.1.1`
- `stackable-webhook` @ `0.3.1`
=> chore: Pre 24.7 releases

Cargo.lock, crates/k8s-version/CHANGELOG.md, crates/k8s-version/Cargo.toml, crates/stackable-certs/CHANGELOG.md, crates/stackable-certs/Cargo.toml, crates/stackable-operator-derive/CHANGELOG.md, crates/stackable-operator-derive/Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/Cargo.toml
This was forgotten in #823.
> [!IMPORTANT]
> After merging, the remote tags need deleting:
> ```sh
> git push --delete origin k8s-version-0.1.1
> git push --delete origin stackable-certs-0.3.1
> git push --delete origin stackable-operator-0.70.0
> git push --delete origin stackable-operator-derive-0.3.1
> git push --delete origin stackable-telemetry-0.2.0
> git push --delete origin stackable-versioned-0.1.1
> git push --delete origin stackable-webhook-0.3.1
> ```
>
> And anyone who has the tags already can remove them with:
> ```sh
> git tag --delete k8s-version-0.1.1
> git tag --delete stackable-certs-0.3.1
> git tag --delete stackable-operator-0.70.0
> git tag --delete stackable-operator-derive-0.3.1
> git tag --delete stackable-telemetry-0.2.0
> git tag --delete …
```
=> Fix: Release bump in Cargo.TOMLs

.github/workflows/pr_pre-commit.yaml, .github/workflows/reviewdog.yaml, .pre-commit-config.yaml, .scripts/tag_and_push_release.sh, .scripts/verify_crate_versions.sh
Added script to help with release crates:
- `.scripts/verify_crate_versions.sh` - used to ensure `CHANGELOG.md` versions match what is in `Cargo.toml`. Useful when creating a release PR.
- `.scripts/tag_and_push_release.sh` - used after a release PR has been merged. It will fetch the origin, and tag each _not yet tagged_ release to the selected commit, and optionally push the tags.
> [!TIP]
> Should we add `.scripts/verify_crate_versions.sh` to the pre-commit hooks? This can save a lot of time and human error.
=> chore: Add crate release helper scripts

.github/ISSUE_TEMPLATE/release-workspace-members.md
Part of https://github.com/stackabletech/issues/pull/602
This adds a new issue template to create a tracking issue for pre-release workspace member updates and releases.
---
**Preview**
> [!NOTE]
> During a Stackable release we update all dependencies in the `operator-rs` repository. After these bumps, each workspace member is released using an appropriate SemVer version. Later, each product operator repository can then use the updates crates.
Replace the items in the task lists below with the applicable Pull Requests
```[tasklist]
```
> [!NOTE]
> The PR is usually titled: `chore: Bump Rust version and workflow actions`
1. Adjust the version of the channel in the `rust-toolchain.toml` file. See <https://releases.rs>.
2. Adjust the version `RUST_TOOLCHAIN_VERSION` in the workflows:
- …
=> chore: Add issue template file

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-operator/src/logging/mod.rs, crates/stackable-telemetry/src/tracing.rs
In #830 the Jaeger `TracingTarget` was removed (as we though it's not used), so that we can bump the `opentelemetry ` crates.
However, [some concerns](https://github.com/stackabletech/operator-rs/pull/830#issuecomment-2269122056) where raised, so we revert the bump and will re-visit it later
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore!: Revert opentelemetry bump with Jaeger removal

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/affinity.rs, crates/stackable-operator/src/utils/crds.rs
Fixup of https://github.com/stackabletech/operator-rs/pull/821
Before
```
The CustomResourceDefinition "druidclusters.druid.stackable.tech" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[coordinators].properties[config].properties[affinity].default.podAffinity: Invalid value: "null": podAffinity in body must be of type object: "null"
* spec.validation.openAPIV3Schema.properties[spec].properties[coordinators].properties[config].properties[affinity].default.podAntiAffinity: Invalid value: "null": podAntiAffinity in body must be of type object: "null"
* spec.validation.openAPIV3Schema.properties[spec].properties[coordinators].properties[config].properties[affinity].default.nodeAffinity: Invalid value: "null": nodeAffinity in body must be of type object: "null"
* …
```
=> fix: Invalid CRD schema for StackableAffinity contents

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/iter.rs
This is an alternative to
```rust
if cond {
// must collect here, since foo.rev() is a distinct type from foo
foo.rev().collect::<Vec<_>>()
} else {
foo.collect()
}
```
That is both much more convenient to use and avoids the buffering and allocation.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add iter::reverse_if helper

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/config/fragment.rs, crates/stackable-operator/src/product_config_utils.rs
Introducing
```
pub const CONFIG_OVERRIDE_FILE_HEADER_KEY
pub const CONFIG_OVERRIDE_FILE_FOOTER_KEY
```
To be used in Superset and Airflow to have unified key names.
Will be used in https://github.com/stackabletech/superset-operator/pull/530, once merged and released
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Add constants for configOverrides file header and footer keys

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
New stackable-operator release
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: release stackable-operator v0.74.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/authentication/mod.rs, crates/stackable-operator/src/commons/authentication/oidc.rs
Came up in https://github.com/stackabletech/nifi-operator/pull/660/files#r1716741090
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Fix the CRD description of ClientAuthenticationDetails

crates/stackable-versioned-macros/src/attrs/common/container.rs, crates/stackable-versioned-macros/src/attrs/common/item.rs, crates/stackable-versioned-macros/src/attrs/field.rs, crates/stackable-versioned-macros/src/attrs/variant.rs, crates/stackable-versioned-macros/src/codegen/common/container.rs, crates/stackable-versioned-macros/src/codegen/common/item.rs, crates/stackable-versioned-macros/src/codegen/common/mod.rs, crates/stackable-versioned-macros/src/codegen/mod.rs, crates/stackable-versioned-macros/src/codegen/venum/mod.rs, crates/stackable-versioned-macros/src/codegen/venum/variant.rs, crates/stackable-versioned-macros/src/codegen/vstruct/field.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned-macros/tests/attributes.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/507, supersedes https://github.com/stackabletech/operator-rs/pull/816.
- Forward all container (struct/enum) and item (field/variant) attributes (this includes doc-comments).
- Allow docs to be added for a specific version (using the `doc` action attribute).
- Add a test case (purposefully ignored) with examples of what should be passed through.
```[tasklist]
```
=> feat(stackable-versioned-macros): Handle attribute forwarding

crates/stackable-versioned-macros/src/attrs/variant.rs
Variant rename validation errors are now reported on the `from` attribute instead of the variant ident.
=> refactor(stackable-versioned): Adjust variant rename validation error span

crates/stackable-versioned-macros/src/codegen/common/container.rs, crates/stackable-versioned-macros/src/codegen/mod.rs, crates/stackable-versioned-macros/src/codegen/venum/mod.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned/CHANGELOG.md
This PR adds visibility forwarding instead of hardcoding `pub` as the generated module visibility. It now uses the visibility of the definition container.
=> feat(stackable-versioned): Forward container visibility

.github/workflows/build.yml, .scripts/verify_crate_versions.sh, Cargo.lock, Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/tests/bad/README.md, crates/stackable-versioned-macros/tests/bad/deprecate.rs, crates/stackable-versioned-macros/tests/bad/deprecate.stderr, crates/stackable-versioned-macros/tests/bad/skip_from_all.rs, crates/stackable-versioned-macros/tests/bad/skip_from_all.stderr, crates/stackable-versioned-macros/tests/bad/skip_from_version.rs, crates/stackable-versioned-macros/tests/bad/skip_from_version.stderr, crates/stackable-versioned-macros/tests/from.rs, crates/stackable-versioned-macros/tests/good/README.md, crates/stackable-versioned-macros/tests/good/attributes_enum.rs, crates/stackable-versioned-macros/tests/good/attributes_struct.rs, crates/stackable-versioned-macros/tests/good/basic.rs, crates/stackable-versioned-macros/tests/good/deprecate.rs, crates/stackable-versioned-macros/tests/good/rename.rs, crates/stackable-versioned-macros/tests/good/skip_from_version.rs, crates/stackable-versioned-macros/tests/trybuild.rs
Some of the tests were just there to ensure code compiles, but they had no assertions.
This is a good opportunity to use [trybuild](https://github.com/dtolnay/trybuild) to make passing and failing code examples.
I have also added docs to the `trybuild.rs` test which gives hints for test writers who might want to enable syntax highlighting and code completion.
```[tasklist]
```
```[tasklist]
```
=> test(stackable-versioned-macros): Use trybuild to test good/bad examples

crates/stackable-versioned-macros/src/attrs/common/item.rs, crates/stackable-versioned-macros/src/attrs/field.rs, crates/stackable-versioned-macros/src/attrs/variant.rs, crates/stackable-versioned-macros/src/codegen/chain.rs, crates/stackable-versioned-macros/src/codegen/common/item.rs, crates/stackable-versioned-macros/src/codegen/venum/variant.rs, crates/stackable-versioned-macros/src/codegen/vstruct/field.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned-macros/tests/good/attributes_enum.rs, crates/stackable-versioned-macros/tests/good/attributes_struct.rs, crates/stackable-versioned-macros/tests/good/basic.rs, crates/stackable-versioned-macros/tests/good/rename.rs, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/src/lib.rs
This PR adds support for type changes of struct fields. This is done by renaming the `renamed()` action to `changed()` and adding a new parameter `from_type` to it. Additionally, `from` will be renamed to `from_name`. 
```[tasklist]
```
=> feat(stackable-versioned): Add support for type changes of fields

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/affinity.rs
-------
This should fix Tilt sometimes refusing to update the CRDs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Unrequire affinity types

.github/workflows/pr_pre-commit.yaml, .pre-commit-config.yaml
Part of https://github.com/stackabletech/issues/issues/637
This fixes two things:
- Install the hadolint binary to be able to run the pre-commit hook
- Set the default language version of `node` to `system`. This fixes issues on NixOS systems.
=> fix(ci): Install hadolint in pre-commit workflow

crates/stackable-versioned-macros/src/codegen/venum/mod.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned/CHANGELOG.md
This PR enables the user to use imported items in container definitions. Previously, the version modules limited the visibility of such items inside said module. Now, using `use super::*` the items can be accessed.
This issue was reported by @sbernauer after a first quick testing round.
=> feat(stackable-versioned): Add 'use super::*' to generated version module

crates/stackable-versioned-macros/src/codegen/common/item.rs, crates/stackable-versioned-macros/src/codegen/venum/variant.rs, crates/stackable-versioned-macros/src/codegen/vstruct/field.rs, crates/stackable-versioned-macros/tests/good/basic.rs, crates/stackable-versioned/CHANGELOG.md
Previously, the type used in fields marked as NoChange in a particular version was incorrect. It used the type of the definition container. The NoChange action now also tracks the field type and can thus generate the correct type.
Discovered by @sbernauer.
=> fix(stackable-versioned): Emit right type for unchanged fields

crates/stackable-versioned-macros/src/attrs/common/item.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned-macros/tests/default/fail/changed.rs, crates/stackable-versioned-macros/tests/default/fail/changed.stderr, crates/stackable-versioned/CHANGELOG.md
This PR adds validation to the `from_name` parameter of the `changed()` action. It is now prohibited to use field / variant names which include the deprecation prefix.
```[tasklist]
```
=> feat(stackable-versioned): Add from_name parameter validation

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/builder/pod/container.rs, crates/stackable-operator/src/builder/pod/mod.rs, crates/stackable-operator/src/builder/pod/security.rs, crates/stackable-operator/src/builder/pod/volume.rs, crates/stackable-operator/src/commons/authentication/oidc.rs, crates/stackable-operator/src/commons/product_image_selection.rs
I was **not** able to update opentelemetry, and would let it to the experts to figure it out, CC @Techassi, @NickLarsenNZ and @nightkr 
I hope the `aws-lc-rs` crate will not cause any problems with Nix. I bumped zookeeper-operator and `make run-dev` worked fine.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Dependecy updates, such as kube 0.95.0 and Kubernetes 0.31

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Add `Hostname` and `KerberosRealmName` types extracted from secret-operator ([#851]).
- Add support for listener volume scopes to `SecretOperatorVolumeSourceBuilder` ([#858]).
- BREAKING: `validation` module now uses typed errors ([#851]).
- Set `checkIncrement` to 5 seconds in Logback config ([#853]).
- Bump Rust dependencies and enable Kubernetes 1.31 (via `kube` 0.95.0) ([#867]).
- Fix the CRD description of `ClientAuthenticationDetails` to not contain internal Rust doc, but a public CRD description ([#846]).
- `StackableAffinity` fields are no longer erroneously marked as required ([#855]).
- BREAKING: `ClusterResources` will now only consider deleting objects that are marked as directly owned (via `.metadata.ownerReferences`) ([#862]).
[#846]: …
=> chore: Release stackable-operator 0.75.0

Cargo.lock, crates/k8s-version/CHANGELOG.md, crates/k8s-version/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
- Add `from_name` parameter validation ([#865]).
- Add new `from_type` parameter to `changed()` action ([#844]).
- Pass through container and item attributes (including doc-comments). Add attribute for version specific docs ([#847]).
- Forward container visibility to generated modules ([#850]).
- Add support for Kubernetes-specific features ([#857]).
- Add `use super::*` to version modules to be able to use imported types ([#859]).
- BREAKING: Rename `renamed()` action to `changed()` and renamed `from` parameter to `from_name` ([#844]).
- Bump syn to 2.0.77 ([#857]).
- Report variant rename validation error at the correct span and trim underscores from variants not using PascalCase ([#842]).
- Emit correct struct field types for fields with no changes (NoChange) …
=> chore: Release stackable-versioned 0.2.0, k8s-version 0.1.2

crates/stackable-versioned-macros/src/codegen/common/container.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned-macros/tests/k8s/pass/crd.rs, crates/stackable-versioned/CHANGELOG.md
This ensures that the user must use a valid version to specify which of the versions of the merged CRDs is stored. Previously, users could provide any `str`, which can lead to runtime errors.
```[tasklist]
```
=> feat(stackable-versioned): Use enum for merged_crd instead of str

crates/stackable-versioned-macros/src/attrs/common/container.rs, crates/stackable-versioned-macros/src/codegen/common/container.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned-macros/tests/k8s/pass/crd.rs, crates/stackable-versioned/CHANGELOG.md
Forwards selected `kube` arguments.
```[tasklist]
```
=> feat(stackable-versioned): Forward selected kube args

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/product_logging/framework.rs
Fix the logback configuration for logback versions from 1.3.6/1.4.6 to 1.3.11/1.4.11.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Logback configuration

crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned-macros/tests/k8s/pass/crd.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/507, follow-up of https://github.com/stackabletech/operator-rs/pull/872#discussion_r1770889930
This PR adjusts the version enum generation used in the `merged_crd` function.
```rust
let merged_crd = Foo::merged_crd(Foo::V1).unwrap();
println!("{}", serde_yaml::to_string(&merged_crd).unwrap());
```
=> refactor(stackable-versioned): Rework version enum for merged_crd

crates/stackable-versioned-macros/src/codegen/chain.rs, crates/stackable-versioned-macros/src/codegen/common/item.rs, crates/stackable-versioned-macros/src/codegen/venum/mod.rs, crates/stackable-versioned-macros/src/codegen/venum/variant.rs, crates/stackable-versioned-macros/src/codegen/vstruct/field.rs, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned-macros/tests/default/pass/deprecate.rs, crates/stackable-versioned-macros/tests/default/pass/deprecate_enum.rs, crates/stackable-versioned-macros/tests/default/pass/deprecate_struct.rs, crates/stackable-versioned-macros/tests/trybuild.rs
With this PR `#[allow(deprecated)]` is only added when needed. Also, `#[deprecated]` is now carried along for fields and variants after they have been marked as deprecated. This currently does not include the note, but the note will be added in the future. To more efficiently store this data, the chain of actions needs to be improved in a follow-up PR.
```[tasklist]
```
=> feat(stackable-versioned): Add conditional allow attr generation

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-operator/src/builder/pod/container.rs, crates/stackable-operator/src/builder/pod/mod.rs, crates/stackable-operator/src/commons/authentication/ldap.rs, crates/stackable-operator/src/commons/s3/helpers.rs, crates/stackable-operator/src/commons/s3/mod.rs, crates/stackable-operator/src/commons/tls_verification.rs, crates/stackable-operator/src/product_logging/framework.rs
Discovered in https://github.com/stackabletech/trino-operator/pull/646
```
2024-09-19T14:50:51.706423Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="trinocluster.trino.stackable.tech" error=reconciler for object TrinoCluster.v1alpha1.trino.stackable.tech/trino.kuttl-test-golden-toucan failed error.sources=[failed to apply StatefulSet for role group worker/default of TrinoCluster.v1alpha1.trino.stackable.te
ch/trino.kuttl-test-golden-toucan, failed to apply patch, unable to patch resource "trino-worker-default", ApiError: failed to create typed patch object (kuttl-test-golden-toucan/trino-worker-default; apps/v1, Kind=StatefulSet): errors: …
```
=> fix!: Avoid clashing volumes and mounts

Cargo.lock, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
- Add forwarding of `singular`, `plural`, and `namespaced` arguments in `k8s()` ([#873]).
- Generate a `Version` enum containing all declared versions as variants ([#872]).
- BREAKING: The `merged_crd` function now accepts `Self` instead of a dedicated `Version` enum ([#875]).
- The `merged_crd` associated function now takes `Version` instead of `&str` as input ([#872]).
[#872]: https://github.com/stackabletech/operator-rs/pull/872
[#873]: https://github.com/stackabletech/operator-rs/pull/873
[#875]: https://github.com/stackabletech/operator-rs/pull/875
=> chore: Release stackable-versioned 0.3.0

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
One could argue this is a bugfix release, but let's play it safe
- Fix the logback configuration for logback versions from 1.3.6/1.4.6 to 1.3.11/1.4.11 ([#874]).
- BREAKING: Avoid colliding volumes and mounts by only adding volumes or mounts if they do not already exist. This makes functions such as `PodBuilder::add_volume` or `ContainerBuilder::add_volume_mount` as well as related ones fallible ([#871]).
- BREAKING: Remove the `unique_identifier` argument from `ResolvedS3Connection::add_volumes_and_mounts`, `ResolvedS3Connection::volumes_and_mounts` and `ResolvedS3Connection::credentials_mount_paths` as it is not needed anymore ([#871]).
[#871]: https://github.com/stackabletech/operator-rs/pull/871
[#874]: https://github.com/stackabletech/operator-rs/pull/874
- Not all of these items are …
=> chore: Release stackable-operator 0.77.0

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-operator/src/builder/pod/container.rs, crates/stackable-operator/src/builder/pod/mod.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Don't always return an error stating volumeMounts are colliding

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/authentication/kerberos.rs, crates/stackable-operator/src/commons/authentication/mod.rs
Required for https://github.com/stackabletech/kafka-operator/pull/762
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: add kerberos authentication provider

.github/workflows/build.yml, Cargo.lock, crates/stackable-operator/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots.snap, crates/stackable-versioned-macros/src/codegen/vstruct/mod.rs, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-versioned/src/lib.rs
This generates helper functions to write the merged CRD to a file and to stdout.
```[tasklist]
```
=> feat(stackable-versioned): Add YAML serialization for merged CRD

Cargo.lock, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
- Add YAML serialization for merged CRD schema. The schema can now be printed to stdout or written to file ([#884]).
- Add snapshot tests to verify generated code matches expected output ([#881]).
[#881]: https://github.com/stackabletech/operator-rs/pull/881
[#884]: https://github.com/stackabletech/operator-rs/pull/884
[0.4.0]: https://github.com/stackabletech/operator-rs/releases/tag/stackable-versioned-0.4.0
=> chore: Release stackable-versioned 0.4.0

crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/fixtures/inputs/default/enum_data_simple.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@enum_data_simple.rs.snap, crates/stackable-versioned-macros/src/codegen/venum/variant.rs, crates/stackable-versioned-macros/src/test_utils.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/642.
- stackable-versioned: Add basic handling for enum variants with data, with a snapshot test.
_TODO: Handle versioning of named/unnamed enum fields_.
```[tasklist]
```
=> feat(stackable-versioned): Add basic handling for enum variants with data

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/listener.rs
See https://github.com/stackabletech/listener-operator/issues/139. In short, it allows users to specify whether they want to prefer exposing IP addresses or hostnames.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add preferred address type field to ListenerClass

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/kvp/annotation/mod.rs, crates/stackable-operator/src/kvp/label/mod.rs, crates/stackable-operator/src/kvp/mod.rs
Fixes #887
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Replace KeyValuePairs' internal BTreeSet with BTreeMap

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Re-export the `YamlSchema` trait and the `stackable-shared` crate as the `shared` module ([#883]).
- BREAKING: Added `preferredAddressType` field to ListenerClass CRD ([#885]).
- BREAKING: The cluster domain (default: `cluster.local`) can now be configured in the individual
operators via the ENV variable `KUBERNETES_CLUSTER_DOMAIN` or resolved automatically by parsing
the `/etc/resolve.conf` file. This requires using `initialize_operator` instead of `create_client`
in the `main.rs` of the individual operators ([#893]).
- BREAKING: The `CustomResourceExt` trait is now re-exported from the `stackable-shared` crate. The
trait functions use the same parameters but return a different error type ([#883]).
- BREAKING: `KeyValuePairs` (as well as `Labels`/`Annotations` via it) is now backed by …
=> chore: Release stackable-operator 0.79.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/fixtures/cluster_domain/fail/no-service-domain.conf, crates/stackable-operator/fixtures/cluster_domain/pass/aws-eks.resolv.conf, crates/stackable-operator/src/utils/cluster_domain.rs
This fixes a bug on AWS EKS:
Given the resolv.conf
```
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 172.20.0.10
options ndots:5
```
the operators logged
`retrieve_cluster_domain: stackable_operator::utils::cluster_domain: Using Kubernetes cluster domain from "/etc/resolv.conf" file cluster_domain=ec2.internal`.
However, they should have used `cluster.local`. This PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Fix Kubernetes cluster domain parsing from resolv.conf

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
Part of https://github.com/stackabletech/operator-rs/issues/898.
This PR releases `stackable-operator-0.80.0` and `stackable-versioned-0.4.1`:
- BREAKING: Don't parse `/etc/resolv.conf` to auto-detect the Kubernetes cluster domain in case it is not explicitly configured. Instead the operator will default to `cluster.local`. We revert this now after some concerns where raised, we will create a follow-up decision instead addressing how we will continue with this ([#896]).
- Update Rust dependencies (Both `json-patch` and opentelemetry crates cannot be updated because of conflicts) ([#897]):
- Bump `kube` to `0.96.0`,
- `rstest` to `0.23.0` and
- `tower-http` to `0.6.1`
- Fix Kubernetes cluster domain parsing from resolv.conf, e.g. on AWS EKS. We now only consider Kubernetes services domains …
=> chore: Release workspace members

.github/ISSUE_TEMPLATE/config.yml
Taken from https://github.com/stackabletech/nifi-operator/blob/2c0df3308987e3da7194169218ccefaa32421e35/.github/ISSUE_TEMPLATE/config.yml. The old issue template pointed at repo discussions, which have long been disabled.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Update the issue template

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/listener.rs
This adds a new `HostnameConservative` preferred address type which uses IP addresses for Node addresses. This should be closer to the old defaults of 0.78.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add "smart" preferred address types

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Add new `PreferredAddressType::HostnameConservative` ([#903]).
- BREAKING: Split `ListenerClass.spec.preferred_address_type` into a new `PreferredAddressType` type. Use `resolve_preferred_address_type()` to access the `AddressType` as before. ([#903])
[#903]: https://github.com/stackabletech/operator-rs/pull/903
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Release stackable-operator 0.81.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/authentication/oidc.rs
Related to https://github.com/stackabletech/nifi-operator/issues/716, but also will fix stuff in all other tools using OIDC (at least Superset and Trino)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix!: Correctly construct OIDC endpoints

crates/stackable-versioned-macros/fixtures/inputs/k8s/module.rs, crates/stackable-versioned-macros/fixtures/inputs/k8s/module_preserve.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/src/codegen/container/mod.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned-macros/src/codegen/module.rs, crates/stackable-versioned/CHANGELOG.md
Previously, when the attribute macro was used on modules and contained structs used K8s specific features, the accompanying code was not generated.
=> fix(stackable-versioned): Emit Kubernetes code in modules

crates/stackable-versioned-macros/fixtures/inputs/k8s/module.rs, crates/stackable-versioned-macros/fixtures/inputs/k8s/module_preserve.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/src/codegen/container/mod.rs, crates/stackable-versioned-macros/src/codegen/module.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/642, follow-up of https://github.com/stackabletech/operator-rs/pull/912
This fixes the wrong generation of Kubernetes specific code which could be triggered by either
- versioning enums alongside structs in a module or
- versioning containers with and without the `k8s` argument in mixed order
=> fix(stackable-versioned): Generate Kubernetes code independent of container order

Cargo.lock, crates/stackable-operator/CHANGELOG.md
Fixes https://github.com/stackabletech/operator-rs/issues/916
Part of https://github.com/stackabletech/issues/issues/677
Note: I ran `cargo update` to get the changes.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Bump rustls from 0.23.15 to 0.23.19 to fix RUSTSEC-2024-0399

crates/stackable-versioned-macros/fixtures/inputs/k8s/renamed_kind.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@renamed_kind.rs.snap, crates/stackable-versioned-macros/src/codegen/container/enum.rs, crates/stackable-versioned-macros/src/codegen/container/mod.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned/CHANGELOG.md
The enum used to generate the merged CRD function now uses the correct ident if customized via `#[kube/k8s(kind = "MyName")]`.
=> fix(stackable-versioned): Emit correct enum based on kube kind argument

crates/stackable-versioned-macros/fixtures/inputs/k8s/basic.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@basic.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@crate_overrides.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@renamed_kind.rs.snap, crates/stackable-versioned-macros/src/codegen/container/mod.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned-macros/src/codegen/module.rs, crates/stackable-versioned/CHANGELOG.md
The generated CRD enum now uses the same visibility as the container definition (standalone mode) or the module (nested mode).
```rust
#[versioned]
pub(crate) struct FooSpec {}
// Expanded to ...
pub enum Foo {}
```
```rust
#[versioned]
pub(crate) struct FooSpec {}
// Expands to ...
pub(crate) enum Foo {}
```
=> feat(stackable-versioned): Support visibility for CRD enum

.github/workflows/build.yml, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@basic_struct.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@deprecate_struct.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@rename.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@skip_from_field.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@basic.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@crate_overrides.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@renamed_kind.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@skip.rs.snap, crates/stackable-versioned-macros/src/codegen/item/field.rs, crates/stackable-versioned/CHANGELOG.md
Remove type comparison and use `.into()` on all field conversions
> [!NOTE]
> The from/to type comparison was semantically invalid as we have no information of the actual type which might still be an equivalent string (eg: `::foo::TypeA` in two versions of a crate are possibly not equivalent).
---
> [!IMPORTANT]
> **CI**: The run_tests dependency on the run_cargodeny job has been removed.
=> fix(stackable-versioned): Remove type comparison and use into() on all field conversions

Cargo.lock, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@basic.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@crate_overrides.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@module_preserve.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__k8s_snapshots@renamed_kind.rs.snap, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-versioned/src/lib.rs
The dependency on stackable-shared can cause some conflicts in projects which use stackable-versioned. This also de-couples Stackable specific code from the versioning macro, which we want to be usable outside of Stackable as well.
Consumers can still generate the merged CRD and then use functions from the `stackable_shared::CustomResourceExt` trait to print or write the YAML.
=> chore(stackable-versioned): Remove {write,print}_merged_crd function

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This release contains:
- Added cert lifetime setter to `SecretOperatorVolumeSourceBuilder` ([#915])
- Replace unmaintained `derivative` crate with `educe` ([#907]).
- Bump dependencies, notably rustls 0.23.15 to 0.23.19 to fix [RUSTSEC-2024-0399] ([#917]).
[#907]: https://github.com/stackabletech/operator-rs/pull/907
[#915]: https://github.com/stackabletech/operator-rs/pull/915
[#917]: https://github.com/stackabletech/operator-rs/pull/917
[RUSTSEC-2024-0399]: https://rustsec.org/advisories/RUSTSEC-2024-0399
=> chore: Release stackable-operator-0.83.0

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/builder/pod/security.rs, crates/stackable-operator/src/logging/controller.rs, crates/stackable-operator/src/logging/k8s_events.rs
**Example implementation:** https://github.com/stackabletech/trino-operator/pull/690
`kube` 0.98.0 introduced a [breaking change](https://github.com/kube-rs/kube/pull/1655), which we propagate to client crates.
See the CHANGELOG for details
Before
```bash
§ kubectl describe trino simple-trino
Type     Reason                Age   From                               Message
----     ------                ----  ----                               -------
Warning  InvalidProductConfig  41s   trinocluster.trino.stackable.tech  invalid product config: invalid configuration found: failed to parse 'XXXXX.0.0' as SemVer version: unexpected character 'X' while parsing major version number
Warning  InvalidProductConfig  81s   trinocluster.trino.stackable.tech  invalid product config: invalid …
```
=> chore!: Bump Rust dependencies, support k8s 1.32

crates/stackable-operator/src/config/fragment.rs, crates/stackable-operator/src/config/merge.rs, crates/stackable-operator/src/config/mod.rs
It's something that has come up time and time again as pretty confusing. This won't cover *everything*, but compared to the complete void before it should hopefully be a better starting point for understanding why it exists, how it ties together, and how it works.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Document config system

Cargo.lock, crates/stackable-telemetry/Cargo.toml, crates/stackable-telemetry/src/tracing/mod.rs, crates/stackable-telemetry/src/tracing/settings/console_log.rs, crates/stackable-telemetry/src/tracing/settings/mod.rs, crates/stackable-telemetry/src/tracing/settings/otlp_log.rs, crates/stackable-telemetry/src/tracing/settings/otlp_trace.rs
Part of https://github.com/stackabletech/issues/issues/639
This adds conversions to turn `(&'static str, LevelFilter)` and `(&'static str, LevelFilter, bool)` into subscriber settings.
=> feat(stackable-telemetry): Add tuple to settings conversions

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This releases `stackbale-operator` 0.84.1 which includes:
- Remove `Merge` trait bound from `erase` and make `product_specific_common_config` public ([#946]).
- BREAKING: Revert the change of appending a dot to the default cluster domain to make it a FQDN, it is now `cluster.local` again. Users can instead explicitly opt-in to FQDNs via the ENV variable `KUBERNETES_CLUSTER_DOMAIN`. ([#947]).
[#946]: https://github.com/stackabletech/operator-rs/pull/946
[#947]: https://github.com/stackabletech/operator-rs/pull/947
=> chore: Release stackable-operator 0.84.1

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/fixtures/helm/input-additional.yaml, crates/stackable-operator/fixtures/helm/input-required.yaml, crates/stackable-operator/fixtures/helm/output.yaml, crates/stackable-operator/src/commons/product_image_selection.rs, crates/stackable-operator/src/product_logging/framework.rs, crates/stackable-operator/src/utils/crds.rs
Fixes https://github.com/stackabletech/operator-rs/issues/937
See e.g. https://github.com/stackabletech/zookeeper-operator/pull/905
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Replace nexus references with oci

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This releases stackbale-operator 0.85.0 which includes:
- Change constant used for product image selection so that it defaults to OCI ([#945](https://github.com/stackabletech/operator-rs/pull/945))
=> chore: Release stackable-operator 0.85.0

.github/workflows/publish-docs.yml
This PR adds a new workflow which will build the crate docs and publishes them on Github Pages. The workflow only runs when changes are pushed/merged to/into main.
=> ci: Publish crate docs on Github Pages

crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned-macros/src/lib.rs
This came up during the Airflow CRD PR review: https://github.com/stackabletech/airflow-operator/pull/581
=> docs(stackable-versioned): Improve docs for module usage

crates/stackable-versioned-macros/fixtures/inputs/default/module_preserve.rs, crates/stackable-versioned-macros/fixtures/inputs/k8s/module_preserve.rs, crates/stackable-versioned-macros/src/attrs/common.rs, crates/stackable-versioned-macros/src/attrs/container.rs, crates/stackable-versioned-macros/src/attrs/module.rs, crates/stackable-versioned-macros/src/codegen/container/enum.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned-macros/src/codegen/mod.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned/CHANGELOG.md
This PR unifies the option interface and moves the `preserve_module` option (which is only available when the macro is used on modules) into the list of `options()`.
**Before**
```rust
#[versioned(
version(name = "v1alpha1"),
preserve_module
)]
mod versioned {
pub struct Foo {
bar: Option<u16>,
}
}
```
**After**
```rust
#[versioned(
version(name = "v1alpha1"),
options(preserve_module)
)]
mod versioned {
pub struct Foo {
bar: Option<u16>,
}
}
```
=> refactor(stackable-versioned): Move preserve_module into options()

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/s3/crd.rs, crates/stackable-operator/src/commons/s3/helpers.rs
Part of https://github.com/stackabletech/docker-images/issues/971.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat(stackable-operator/s3connection): Add region field defaulting to us-east-1

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/s3/crd.rs
BREAKING: Improve `AwsRegion::name()` ergonomics: borrow self and return `Option<&str>`.
=> fix(stackable-operator): Improve AwsRegion::name() ergonomics 

crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned/README.md
This PR improves the documentation of the following topics:
- Which version the defined struct represents
- What the `merged_crd` method does
=> docs(stackable-versioned): Improve various sections of docs

crates/stackable-versioned-macros/fixtures/inputs/default/generics_enum.rs, crates/stackable-versioned-macros/fixtures/inputs/default/generics_module.rs, crates/stackable-versioned-macros/fixtures/inputs/default/generics_struct.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@generics_enum.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@generics_module.rs.snap, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@generics_struct.rs.snap, crates/stackable-versioned-macros/src/codegen/container/enum.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/642, came up in https://github.com/stackabletech/operator-rs/pull/968
This PR adds basic support for generic types in struct and enum definitions. More complex topics involving field actions are not covered by this. This (might) eventually come in follow-up PR.
=> feat(stackable-versioned): Add support for generics

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md
Tested the bump with trino-operator
Remaining, non-trivial bumps:
```
Upgrading const-oid ^0.9.6 -> ^0.10.0
Upgrading rand_core ^0.6.4 -> ^0.9.2
Upgrading json-patch ^3.0.1 -> ^4.0.0
Upgrading opentelemetry_sdk ^0.23.0 -> ^0.28.0
Upgrading tracing-opentelemetry ^0.24.0 -> ^0.29.0
Upgrading opentelemetry ^0.23.0 -> ^0.28.0
Upgrading opentelemetry-appender-tracing ^0.4.0 -> ^0.28.1
Upgrading opentelemetry-otlp ^0.16.0 -> ^0.28.0
Upgrading opentelemetry-semantic-conventions ^0.15.0 -> ^0.28.0
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore!: Bump strum, rand and convert_case

crates/stackable-versioned-macros/fixtures/inputs/default/submodule.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@submodule.rs.snap, crates/stackable-versioned-macros/src/codegen/module.rs, crates/stackable-versioned-macros/src/lib.rs, crates/stackable-versioned-macros/tests/default/fail/submodule_invalid_name.rs, crates/stackable-versioned-macros/tests/default/fail/submodule_invalid_name.stderr, crates/stackable-versioned-macros/tests/default/fail/submodule_use_statement.rs, crates/stackable-versioned-macros/tests/default/fail/submodule_use_statement.stderr, crates/stackable-versioned/CHANGELOG.md
This PR allows users to define modules in the `versioned` module, which allows composition of imports which then produces easier to consume imports in downstream code.
**Example**
```rust
// In crate/crd/mod.rs
#[versioned(
version(name = "v1alpha1"),
version(name = "v1")
)]
mod versioned {
mod v1alpha1 {
pub use crate::crd::oidc::v1alpha1::*
pub use crate::crd::tls::v1alpha1::*
}
struct Foo {
bar: usize,
}
}
```
=> feat(stackable-versioned): Re-emit and merge modules in versioned modules

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
Part of <https://github.com/stackabletech/operator-rs/issues/970>
- BREAKING: Update `strum` to `0.27.1` (clients need to also update strum!), `rand` to `0.9.0` and `convert_case` to `0.8.0` ([#972]).
[#972]: https://github.com/stackabletech/operator-rs/pull/972
- Add support for re-emitting and merging modules defined in versioned modules ([#971]).
- Add basic support for generic types in struct and enum definitions ([#969]).
- BREAKING: Move `preserve_module` option into `options` to unify option interface ([#961]).
[#961]: https://github.com/stackabletech/operator-rs/pull/961
[#969]: https://github.com/stackabletech/operator-rs/pull/969
[#971]: https://github.com/stackabletech/operator-rs/pull/971
=> chore: Release stackable-operator-0.87.0 and stackable-versioned-0.6.0

.github/workflows/build.yml
This bumps the broken cargo-deny 2.0.6 action to 2.0.10.
=> ci: Bump broken cargo-deny action

Cargo.lock, crates/stackable-certs/src/ca/mod.rs, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/rbac.rs, crates/stackable-operator/src/commons/s3/crd.rs, crates/stackable-operator/src/config/fragment.rs, crates/stackable-operator/src/config/merge.rs, crates/stackable-operator/src/cpu.rs, crates/stackable-operator/src/memory.rs, crates/stackable-operator/src/status/condition/operations.rs, crates/stackable-operator/src/time/serde_impl.rs, crates/stackable-telemetry/src/instrumentation/axum/extractor.rs, crates/stackable-telemetry/src/instrumentation/axum/injector.rs, crates/stackable-versioned-macros/src/codegen/changes.rs, crates/stackable-versioned-macros/src/codegen/container/enum.rs, crates/stackable-versioned-macros/src/codegen/container/mod.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned-macros/src/codegen/mod.rs, crates/stackable-versioned-macros/src/codegen/module.rs
This PR adjusts the region field according to this https://github.com/stackabletech/decisions/issues/46#issuecomment-2703905958
```yaml
region:
name: eu-central-1
```
=> refactor: Adjust S3 region field structure

deny.toml
This PR updates the ignored Rust advisories. The `backoff` and `paste` advisories came up in #976.
=> chore: Update ignored advisories

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/s3/crd.rs
Needed for https://github.com/stackabletech/druid-operator/pull/696#issuecomment-2724018547
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Add Region::is_default_config function

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/logging/mod.rs
This reverts commit cbb7cc5da1a9452886f2917e5c39cf0d992926db.
This revert is needed, because another `stackable-operator` release before SDP 25.3.0 is required to fix a breaking change in `kube` which is only encountered during runtime.
```
2025-03-19T14:37:07.285064Z  INFO stackable_operator::utils::logging: Starting Stackable Operator for Apache Superset
2025-03-19T14:37:07.285095Z  INFO stackable_operator::utils::logging: This is version 0.0.0-dev (Git information: c7273b5), built for x86_64-unknown-linux-gnu by rustc 1.84.1 (e71f9a9a9 2025-01-27) at Wed, 19 Mar 2025 14:14:33 +0000
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.25/src/crypto/mod.rs:249:14:
no process-level CryptoProvider available -- call …
```
=> revert: Temporarily revert #950

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md
Needs #987
https://github.com/kube-rs/kube/pull/1717 removed `ring` as the default crypto provider which was always present even though default features were turned off using `default-features = false`. Setups which disabled default features **without** manually specifying the crypto provider using a feature accidentally worked. After `kube` 0.99.0 was released, these setups broke, as did our one.
The changes needed are outlined in https://github.com/kube-rs/kube/pull/1720.
**Runtime error**
```
2025-03-19T14:37:07.285064Z  INFO stackable_operator::utils::logging: Starting Stackable Operator for Apache Superset
2025-03-19T14:37:07.285095Z  INFO stackable_operator::utils::logging: This is version 0.0.0-dev (Git information: c7273b5), built for x86_64-unknown-linux-gnu by rustc 1.84.1 …
```
=> chore: Enable kube/ring feature

crates/stackable-versioned-macros/fixtures/inputs/default/generics_defaults.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@generics_defaults.rs.snap, crates/stackable-versioned-macros/src/codegen/container/enum.rs, crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned/CHANGELOG.md
Part of https://github.com/stackabletech/issues/issues/642, needed for #968 
Correctly emit type parameter defaults in generated enum and struct definitions.
=> fix(stackable-versioned): Emit type parameter defaults

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cluster_resources.rs
Part of : https://github.com/stackabletech/spark-k8s-operator/issues/284
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Add Deployments to ClusterResources

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cluster_resources.rs, crates/stackable-operator/src/logging/mod.rs
> [!CAUTION]
> This PR must not be merged before the SDP 25.3.0 release.
This PR re-introduces changes from #950 which were reverted in #987.
=> chore(stackable-operator): Re-introduce #950

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cluster_resources.rs, crates/stackable-operator/src/status/condition/deployment.rs, crates/stackable-operator/src/status/condition/mod.rs
Part of : https://github.com/stackabletech/spark-k8s-operator/issues/284
This is a literal adaptation of the `StatefulSetConditionBuilder` because cleanup and consolidation are out of scope for the issue above.
Condition builders are used by SDP operators to monitor workloads and update stacklet status fields in a standardized way. This adds a condition builder for `Deployments`.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: add DeploymentConditionBuilder

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-telemetry/src/tracing/mod.rs, crates/stackable-telemetry/src/tracing/settings/file_log.rs, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml
This releases stackable-operator 0.88.0 and stackable-versioned 0.7.1.
- Add Deployments to `ClusterResource`s ([#992]).
- Add `DeploymentConditionBuilder`  ([#993]).
- Deprecate `stackable_operator::logging::initialize_logging()`.
It's recommended to use `stackable-telemetry` or `#[allow(deprecated)]` instead ([#950], [#989]).
[#950]: https://github.com/stackabletech/operator-rs/pull/950
[#989]: https://github.com/stackabletech/operator-rs/pull/989
[#992]: https://github.com/stackabletech/operator-rs/pull/992
[#993]: https://github.com/stackabletech/operator-rs/pull/993
- Correctly emit generic type parameter defaults in enum/struct definition blocks ([#991]).
[#991]: https://github.com/stackabletech/operator-rs/pull/991
=> chore: Release stackable-operator 0.88.0, stackable-versioned 0.7.1

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/Cargo.toml
This releases stackable-operator 0.89.0 and stackable-telemetry 0.4.0.
- Add more granular telemetry related arguments to `ProductOperatorRun` ([#977]).
- `--no-console-output`: Disables output of `tracing` events to the console (stdout)
- `--rolling-logs`: Enables output `tracing` events to a rolling log file
- `--rolling-logs-period`: Sets the time period after which log files are rolled over
- `--otlp-traces`: Enables exporting of traces via OTLP
- `--otlp-logs`: Enables exporting of logs via OTLP
- BREAKING: Remove `--tracing-target` argument and field from `ProductOperatorRun`.
Use the new, more granular arguments instead ([#977]).
- BREAKING: Remove `initialize_logging` helper function from `stackable_operator::logging` ([#977]).
- Remove `opentelemetry-jaeger` dependency ([#977]). …
=> chore: Release stackable-operator 0.89.0, stackable-telemetry 0.4.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cli.rs
_Sigh, no words... This slipped my mind_
=> chore: Make TelemetryArguments fields pub

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This releases stackable-operator 0.89.1:
- Make fields of `TelemetryArguments` public ([#998]).
[#998]: https://github.com/stackabletech/operator-rs/pull/998
=> chore: Release stackable-operator 0.89.1

Cargo.lock, deny.toml
- Remove advisories RUSTSEC-2024-0384, RUSTSEC-2024-0436 & RUSTSEC-2025-0012 from ignore list as they are no longer encountered.
- bump `tokio` to `1.44.2`
=> chore: Address rustsec advisories

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This releases stackable-operator 0.90.0
- BREAKING: Inject vector aggregator address into vector config file using an environment variable ([#1000]).
[#1000]: https://github.com/stackabletech/operator-rs/pull/1000
=> chore: Release stackable-operator 0.90.0

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/Cargo.toml
This releases stackable-operator 0.91.0 and stackable-telemetry 0.5.0.
- BREAKING: Remove `cli::TelemetryArguments` and `cli::RollingPeriod` which are both replaced by
types from `stackable_telemetry` ([#1001]).
- BREAKING: The `ProductOperatorRun` struct now uses `stackable_telemetry::tracing::TelemetryOptions`
for the `telemetry_arguments` field ([#1001]).
- Add new `Tracing::pre_configured` method ([#1001]).
- Add `TelemetryOptions` struct and `RollingPeriod` enum
- Add `clap` feature to enable `TelemetryOptions` being used as CLI arguments
- BREAKING: Change `FileLogSettingsBuilder::with_rotation_period` to take `impl Into<Rotation>`
instead of `Rotation` ([#1001]).
[#1001]: https://github.com/stackabletech/operator-rs/pull/1001
=> chore: Release stackable-operator 0.91.0, stackable-telemetry 0.5.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing/mod.rs
Part of https://github.com/stackabletech/issues/issues/639
- `CONSOLE_LOG_DISABLED` (`--console-log-disabled`): Disables console logs when set to `true`.
- `CONSOLE_LOG_LEVEL`: Set the log level for the console logs.
- `FILE_LOG_DIRECTORY` (`--file-log-directory`): Enable the file logs and set the file log directory.
- `FILE_LOG_ROTATION_PERIOD` (`--file-log-rotation-period`): Set the rotation period of log files
- `FILE_LOG_LEVEL`: Set the log level for file logs
- `OTEL_LOG_EXPORTER_ENABLED` (`--otel-log-exporter-enabled`): Enable exporting OTEL logs
- `OTEL_LOG_EXPORTER_LEVEL`: Set the log level for OTEL logs
- `OTEL_TRACE_EXPORTER_ENABLED` (`--otel-trace-exporter-enabled`): Enable exporting OTEL traces
- `OTEL_TRACE_EXPORTER_LEVEL`: Set the log level for OTEL traces
=> refactor!: Update telemetry related env vars and CLI args

crates/stackable-operator/CHANGELOG.md, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing/mod.rs, crates/stackable-telemetry/src/tracing/settings/file_log.rs
Part of https://github.com/stackabletech/issues/issues/639
BREAKING: Allow configuration of `file_log_max_files`.
- Adds the `--file-log-max-files` CLI argument (env: `FILE_LOG_MAX_FILES`).
- `FileLogSettingsBuilder::with_max_log_files` which took a `usize` was renamed to
`FileLogSettingsBuilder::with_max_files` and now takes an `impl Into<Option<usize>>`
for improved builder ergonomics.
=> feat(stackable-telemetry)!: Allow configuration of `file_log_max_files`

crates/stackable-operator/CHANGELOG.md, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing/mod.rs, crates/stackable-telemetry/src/tracing/settings/console_log.rs
Add support for JSON console log output.
A new CLI argument was added: `--console-log-format`. It can be set to `plain` (default), or `json`.
=> feat(stackable-telemetry): Support JSON console log output

crates/stackable-operator/CHANGELOG.md
#968 introduced a slightly wrong changelog which is corrected by this PR.
=> chore: Correct stackable-operator changelog

.github/ISSUE_TEMPLATE/release-workspace-members.md
=> chore(issue_templates): Remove tasklists

Cargo.lock, Cargo.toml, crates/stackable-telemetry/CHANGELOG.md, crates/stackable-telemetry/src/tracing/mod.rs, crates/stackable-versioned-macros/fixtures/README.md
Leftovers
```
cargo +nightly update -Z unstable-options --breaking --dry-run
Upgrading const-oid ^0.9.6 -> ^0.10.1
Upgrading rand_core ^0.6.4 -> ^0.9.3
```
can not be bumped because of transitive dependecy version mismatches.
=> chore: Dependecy bumps

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/crd/authentication/core/mod.rs, crates/stackable-operator/src/crd/authentication/ldap/mod.rs, crates/stackable-operator/src/crd/authentication/ldap/v1alpha1_impl.rs, crates/stackable-operator/src/crd/authentication/oidc/mod.rs, crates/stackable-operator/src/crd/authentication/oidc/v1alpha1_impl.rs, crates/stackable-operator/src/crd/s3/bucket/mod.rs, crates/stackable-operator/src/crd/s3/bucket/v1alpha1_impl.rs, crates/stackable-operator/src/crd/s3/connection/mod.rs, crates/stackable-operator/src/crd/s3/connection/v1alpha1_impl.rs, crates/stackable-operator/src/crd/s3/mod.rs
This PR adds public re-exports for versioned CRD-specific error types.
> [!NOTE]
> The adjustments to the doc comments might need to be tweaked.
=> fix(stackable-operator): Re-export versioned error types

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/crd/listener/mod.rs, crates/stackable-operator/src/crd/s3/mod.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Re-export versioned common enums

crates/stackable-versioned-macros/fixtures/inputs/default/basic_struct.rs, crates/stackable-versioned-macros/fixtures/snapshots/stackable_versioned_macros__test__default_snapshots@basic_struct.rs.snap, crates/stackable-versioned-macros/src/codegen/changes.rs, crates/stackable-versioned-macros/src/codegen/item/field.rs, crates/stackable-versioned-macros/tests/default/pass/added.rs, crates/stackable-versioned-macros/tests/trybuild.rs, crates/stackable-versioned/CHANGELOG.md
Found by @sbernauer
```rust
#[versioned(
version(name = "v1alpha1"),
version(name = "v1alpha2"),
version(name = "v1beta1"),
version(name = "v1")
)]
struct Foo {
username: String,
#[versioned(added(since = "v1alpha2"))]
first_name: String,
#[versioned(added(since = "v1beta1"))]
last_name: String,
}
```
=> fix(stackable-versioned): Handle fields added in later versions

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/builder/pod/container.rs, crates/stackable-operator/src/crd/s3/connection/mod.rs
Leftovers (cant update)
```bash
cargo +nightly update -Z unstable-options --breaking --dry-run
Upgrading const-oid ^0.9.6 -> ^0.10.1
Upgrading rand_core ^0.6.4 -> ^0.9.3
```
=> chore!: Bump kube to 1.0.0, k8s-openapi to 0.25.0

Cargo.lock, crates/k8s-version/CHANGELOG.md, crates/k8s-version/Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
This PR releases k8s-version 0.1.3 and stackable-operator 0.93.0:
- Add support for serialization and deserialization via `serde`. This feature is enabled via the
`serde` feature flag ([#1034]).
[#1034]: https://github.com/stackabletech/operator-rs/pull/1034
- BREAKING: Version common CRD structs and enums ([#968]).
- All CRD-related types and function now reside in the `stackable_operator::crd` module.
- Each CRD-related struct and enum has been versioned. The initial version is `v1alpha1`.
- The `static` authentication provider must now be imported using `r#static`.
- Import are now more granular in general.
- BREAKING: Update to `kube` to `1.0.0` and `k8s-openapi` to `0.25.0`.
Use k8s `1.33` for compilation ([#1037]).
- Re-export versioned CRD-specific error types ([#1025]).
- …
=> chore: Release k8s-version 0.1.3 and stackable-operator 0.93.0

crates/stackable-operator/src/crd/authentication/core/mod.rs, crates/stackable-operator/src/crd/authentication/oidc/mod.rs
The audience for doc-comments are quite different to those for the hosted CRD docs, so we should override CRD descriptions when they contain developer-level details.
> [!NOTE]
> There are likely more changes required, but these are the few I noticed when bumping stackable-operator for druid-operator.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(stackable-operator): Separate some developer docs from CRD descriptions

crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/src/constants.rs, crates/stackable-webhook/src/options.rs
Needed for CRD conversions.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore!(stackable-webhook): Default listen address to bind to all addresses

crates/stackable-versioned-macros/src/codegen/container/struct.rs, crates/stackable-versioned-macros/tests/inputs/k8s/pass/basic.rs, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@basic.rs.snap, crates/stackable-versioned/CHANGELOG.md
With this fix, the macro correctly generates the `#[kube(status = ...)]` attribute again. This regression was accidentally introduced in #1033.
=> fix(stackable-versioned): Correctly emit `#[kube(status = ...)]` attribute

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md
OTel 0.30 is blocked by https://github.com/tokio-rs/tracing-opentelemetry/pull/205
Lefovers
```
Upgrading const-oid ^0.9.6 -> ^0.10.1
Upgrading rand_core ^0.6.4 -> ^0.9.3
Upgrading schemars ^0.8.21 -> ^0.9.0
Upgrading opentelemetry ^0.29.1 -> ^0.30.0
Upgrading opentelemetry-appender-tracing ^0.29.1 -> ^0.30.0
Upgrading opentelemetry-otlp ^0.29.0 -> ^0.30.0
Upgrading opentelemetry_sdk ^0.29.0 -> ^0.30.0
```
=> chore!: Update kube to 1.1.0

.github/pull_request_template.md, .pre-commit-config.yaml
- Updates pre-commit dependencies (to get rid of a warning among other things)
- Updates PR template
=> chore: Update pre-commit hooks

rust-toolchain.toml
This fixes the current pre-commit (clippy) failures by installing the "default" profile.
In the future, we want to instead explicitly list the components for each toolchain in the `pre-commit` action instead. This will internally most likely use a custom "install rust" action which allows to install multiple toolchains at once.
=> chore: Use the default profile for the stable Rust toolchain

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/crds/DummyCluster.yaml, crates/stackable-operator/src/status/condition/daemonset.rs, crates/stackable-operator/src/status/condition/deployment.rs, crates/stackable-operator/src/status/condition/mod.rs, crates/stackable-operator/src/status/condition/operations.rs, crates/stackable-operator/src/status/condition/statefulset.rs
fixes https://github.com/stackabletech/operator-rs/issues/1032
Zookeeper status: 
```
status:
conditions:
- lastTransitionTime: "2025-06-12T10:58:13Z"
message: All StatefulSet have the requested amount of ready replicas.
status: "True"
type: Available
- message: The cluster is reconciled normally.
status: "False"
type: ReconciliationPaused
- message: The cluster is running.
status: "False"
type: Stopped
discoveryHash: "5807873964697571649"
```
```
The `lastUpdatedTime` was removed from the `ClusterStatus` of each operator. Users previously relying on that value should migrate to `lastTransitionTime`.
```
=> Remove last_ update_time from ClusterCondition

crates/stackable-versioned-macros/src/codegen/module.rs
This improves DX by emitting an error when invalid items are added to the versioned module:
=> fix(stackable-versioned): Emit an error when invalid items are added to the versioned module

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/commons/rbac.rs
=> fix: remove role binding to legacy service account  name

crates/stackable-certs/CHANGELOG.md, crates/stackable-certs/src/ca/consts.rs, crates/stackable-certs/src/ca/mod.rs, crates/stackable-webhook/src/tls.rs
As https://github.com/stackabletech/operator-rs/pull/1044 didn't move along, splitting the relevant change out to unblock CRD versioning.
=> feat!(stackable-certs): Support adding SAN entries

crates/stackable-versioned-macros/src/codegen/container/struct/k8s.rs, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@basic.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@conversion_tracking.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@crate_overrides.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@module.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@module_preserve.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@renamed_kind.rs.snap, crates/stackable-versioned-macros/tests/snapshots/stackable_versioned_macros__snapshot_tests__k8s@shortnames.rs.snap, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/tests/conversions.rs, crates/stackable-versioned/tests/merged_crd.rs, crates/stackable-versioned/tests/person.rs
This is rather curious because the previous generated code should result in compiler errors. The expanded code does not error, but manually copy+pasting the generated code reveals the compiler error as expected:
```
error[E0170]: pattern binding `V1Alpha1` is named the same as one of the variants of the type `FooVersion`
--> crates/stackable-versioned-macros/tests/test.rs:324:13
|
324 |             V1Alpha1 => "v1alpha1",
|             ^^^^^^^^ help: to match on the variant, qualify the path: `FooVersion::V1Alpha1`
|
= note: `#[deny(bindings_with_variant_name)]` on by default
``` 
The incorrect match resulted in `as_str` to always return the earliest version (usually `v1alpha1`). This resulted in the wrong version to be marked as stored when calling `Foo::merged_crd`.
=> fix(stackable-versioned): Emit correct match arms for version enum

Cargo.lock, Cargo.toml, crates/stackable-webhook/src/lib.rs, crates/stackable-webhook/src/servers/conversion.rs
Leftovers we can't bump yet
```
$ cargo +nightly update -Z unstable-options --breaking --dry-run
Upgrading const-oid ^0.9.6 -> ^0.10.1
Upgrading rand_core ^0.6.4 -> ^0.9.3
Upgrading schemars ^0.8.21 -> ^1.0.3
```
Also fix new appearing clippy warnings and a typo
=> chore: Bump opentelemetry crates

Cargo.lock, Cargo.toml, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-operator/src/client.rs, crates/stackable-operator/src/utils/cluster_info.rs, crates/stackable-operator/src/utils/kubelet.rs, crates/stackable-operator/src/utils/mod.rs
Fixes https://github.com/stackabletech/issues/issues/662
=> feat: automatic cluster detection

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-shared/CHANGELOG.md, crates/stackable-shared/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/Cargo.toml
This PR releases
- Add `ProbeBuilder` to build Kubernetes container probes ([#1078]).
- Re-export `stackable-certs` and `stackable-webhook` crates ([#1074]).
- BREAKING: Add two new required CLI arguments: `--operator-namespace` and `--operator-service-name`.
These two values are used to construct the service name in the CRD conversion webhook ([#1066]).
- Re-export `stackable-certs` and `stackable-webhook` crates ([#1074]).
- BREAKING: The `ResolvedProductImage` field `app_version_label` was renamed to `app_version_label_value` to match changes to its type ([#1076]).
- BREAKING: Rename two fields of the `ProductOperatorRun` struct for consistency and clarity ([#1066]):
- `telemetry_arguments` -> `telemetry`
- `cluster_info_opts` -> `cluster_info`
- BREAKING: Some modules have been moved …
=> chore: Release workspace members (stackable-operator 0.95.0)

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-operator/src/builder/pod/probe.rs
Small improvement of https://github.com/stackabletech/operator-rs/pull/1078
=> fix: Derive Clone for ProbeBuilder and ProbeAction

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cli.rs
We currently have a bug that opa-bundle-builder or user-info-fetcher take an `ProductOperatorRun`, causing
```bash
bundle-builder error: the following required arguments were not provided:                                                                                                
bundle-builder   --operator-namespace <OPERATOR_NAMESPACE>                                                                                                               
bundle-builder   --operator-service-name <OPERATOR_SERVICE_NAME>                                                                                                         
bundle-builder …
```
=> feat!: Add cli::CommonOptions struct

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml
- Add a `cli::CommonOptions` struct, which can be used for non-operator Stackable tools ([#1083]).
- BREAKING: The `telemetry` and `cluster_info` fields of `ProductOperatorRun` have moved below the `common` field ([#1083]).
[#1083]: https://github.com/stackabletech/operator-rs/pull/1083
=> chore: Release stackable-operators 0.96.0

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/cli.rs, crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/src/servers/conversion.rs
We got feedback that some customers value breaking their cluster over giving operators RBAC permissions for CRDs :D
So WCGW?
=> feat!: Add a new CLI flag/env to disabling CRD maintenance

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/config/merge.rs
Remove the Merge implementation for PodTemplateSpec
It was broken because the instance was overriden by the given defaults.
This function is not used by the Stackable operators. Even if it is used by other operators, it is better to remove it than to "silently" switch the parameters.
=> feat: Remove the Merge implementation for PodTemplateSpec

Cargo.lock, crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/Cargo.toml, crates/stackable-versioned-macros/Cargo.toml, crates/stackable-versioned/CHANGELOG.md, crates/stackable-versioned/Cargo.toml, crates/stackable-webhook/CHANGELOG.md, crates/stackable-webhook/Cargo.toml
- BREAKING: Add a new CLI flag/env to disabling CRD maintenance: `--disable-crd-maintenance` ([#1085]).
- BREAKING: Remove the Merge implementation for PodTemplateSpec ([#1087]).
It was broken because the instance was overridden by the given defaults.
This function is not used by the Stackable operators.
- Don't default the `termination_grace_period` of the `ProbeBuilder` to 0, as this is an invalid value ([#1090]).
[#1085]: https://github.com/stackabletech/operator-rs/pull/1085
[#1087]: https://github.com/stackabletech/operator-rs/pull/1087
[#1090]: https://github.com/stackabletech/operator-rs/pull/1090
- Add new `#[versioned(hint)]` argument to provide type hints for struct fields ([#1089]).
- `#[versioned(hint(option))]` for fields wrapped in an `Option`. Generates `.map(Into::into)`. …
=> chore: Release workspace members (stackable-operator 0.97.0)

crates/stackable-operator/CHANGELOG.md, crates/stackable-operator/src/builder/pod/container.rs, crates/stackable-operator/src/validation.rs
Follow up to https://github.com/stackabletech/operator-rs/pull/1064, which introduced uppercase characters in domain names. The updated format was used for domain names as well as container names in Kubernetes for example. But, actually, the Kubernetes RFC 1123 specification is slightly different, only allowing lowercase characters, see https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names. This PR adjusts the separation of usage between the two.
=> fix: Don't allow uppercase characters in Kubernetes object names
